import type { EventTemplate } from '../types';

export const franchiseIdentityEventDeck: EventTemplate[] = [
// ─── Phase 4: New Arc A — franchise-identity ────────────────────────────────

    {
      id: 'franchise-creative-audit',
      category: 'creative',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      requiresFlag: 'franchise_rights',
      blocksArc: { id: 'franchise-identity', status: 'resolved' },
      title: 'Franchise DNA Review',
      decisionTitle: 'Franchise DNA Review',
      body: 'A creative consultant hired by your distributor argues the sequel has drifted from what made the original connect.',
      cooldownWeeks: 8,
      baseWeight: 0.9,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        arcId: 'franchise-identity',
        arcStage: 0,
        title: 'Franchise DNA Review',
        body: `${projectTitle ?? 'The sequel'} is being challenged on franchise identity before cameras finish rolling.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Commission A Legacy Audit',
            preview: 'Costs time and money. Clarifies what the franchise actually is.',
            cashDelta: -160_000,
            scriptQualityDelta: 0.2,
            hypeDelta: 0,
            criticsDelta: 2,
            setFlag: 'franchise_legacy_reviewed',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Invite The Original Director Back',
            preview: 'Goodwill play. Sets expectations for their involvement.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: 2,
            criticsDelta: 1,
            setFlag: 'franchise_original_director',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Dismiss The Notes',
            preview: 'Saves nothing. The drift will show on screen.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
            audienceDelta: 1,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'franchise-voice-selection',
      category: 'creative',
      scope: 'project',
      targetPhases: ['preProduction'],
      requiresArc: { id: 'franchise-identity', minStage: 1, status: 'active' },
      title: 'Choosing The Franchise Voice',
      decisionTitle: 'Choosing The Franchise Voice',
      body: 'The audit crystallized a choice: auteur prestige, commercial certainty, or continuity with the current team.',
      cooldownWeeks: 10,
      baseWeight: 0.95,
      minWeek: 10,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        arcId: 'franchise-identity',
        arcStage: 1,
        title: 'Choosing The Franchise Voice',
        body: `${projectTitle ?? 'This franchise entry'} needs a directional call before final prep.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Hire The Auteur',
            preview: 'Prestige ceiling rises. Commercial floor drops.',
            cashDelta: -200_000,
            scriptQualityDelta: 0.5,
            hypeDelta: 0,
            criticsDelta: 4,
            audienceDelta: -2,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Hire The Commercial Director',
            preview: 'Safe opening upside. Critics will notice.',
            cashDelta: -180_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            criticsDelta: -2,
            audienceDelta: 4,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Keep The Current Director',
            preview: 'No disruption. Incremental improvement.',
            cashDelta: 0,
            scriptQualityDelta: 0.1,
            hypeDelta: 0,
            setArcStage: 2,
          },
        ],
      }),
    },
    {
      id: 'franchise-legacy-test',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      requiresArc: { id: 'franchise-identity', minStage: 2, status: 'active' },
      title: 'The Franchise Accountability Moment',
      decisionTitle: 'The Franchise Accountability Moment',
      body: 'Tracking says audiences want one answer: does this sequel earn its place, or coast on brand familiarity?',
      cooldownWeeks: 12,
      baseWeight: 0.85,
      minWeek: 12,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        arcId: 'franchise-identity',
        arcStage: 2,
        title: 'The Franchise Accountability Moment',
        body: `${projectTitle ?? 'The sequel campaign'} must pick a positioning thesis now.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Campaign On Legacy And Continuity',
            preview: 'Audience-maximizing framing. Critics read it as defensive.',
            cashDelta: -240_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            audienceDelta: 3,
            criticsDelta: -1,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: "Campaign On What's New",
            preview: 'More expensive. Signals creative evolution.',
            cashDelta: -280_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 3,
            audienceDelta: 1,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Minimal Campaign - Let The Film Speak',
            preview: "Both camps notice you didn't commit. Momentum stalls.",
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
            audienceDelta: -1,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'fatigue-signal-emerges',
      category: 'marketing',
      scope: 'studio',
      requiresFlag: 'franchise_committed',
      blocksArc: { id: 'franchise-fatigue', status: 'resolved' },
      title: 'Franchise Wear Signal',
      decisionTitle: 'Franchise Wear Signal',
      body: "Social listening shows early 'franchise fatigue' sentiment across your repeat-release audience cohorts.",
      cooldownWeeks: 12,
      baseWeight: 0.85,
      minWeek: 12,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'marketing',
        arcId: 'franchise-fatigue',
        arcStage: 0,
        title: 'Franchise Wear Signal',
        body: "It's not a crisis yet, but the signal is strong enough to force policy choices.",
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Commission Audience Research',
            preview: 'Buys informed options. Modest upside.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: 1,
            setFlag: 'franchise_fatigue_warning',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Fast-Track A Reinvention Plan',
            preview: 'More expensive but gets ahead of the problem.',
            cashDelta: -200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 2,
            setFlag: 'franchise_fatigue_warning',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Dismiss As Noise',
            preview: 'Cheaper to ignore. Fatigue compounds.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: -1,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'franchise-reinvention-pitch',
      category: 'creative',
      scope: 'studio',
      requiresArc: { id: 'franchise-fatigue', minStage: 1, status: 'active' },
      title: 'The Reinvention Pitch',
      decisionTitle: 'The Reinvention Pitch',
      body: 'Three visions emerge: legacy continuation, genre pivot, or a planned hiatus to rebuild demand.',
      cooldownWeeks: 10,
      baseWeight: 0.9,
      minWeek: 14,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'creative',
        arcId: 'franchise-fatigue',
        arcStage: 1,
        title: 'The Reinvention Pitch',
        body: 'Leadership must set direction before the next announcement cycle.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Legacy Continuation',
            preview: 'Safest path. Diminishing returns if fatigue is real.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: 3,
            criticsDelta: -1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Genre Pivot',
            preview: 'Expensive risk. Earns critical credibility.',
            cashDelta: -300_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 4,
            audienceDelta: -2,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Voluntary Hiatus',
            preview: 'Distributor friction. Audience patience resets.',
            cashDelta: -150_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: -2,
            audienceDelta: 2,
            setArcStage: 2,
          },
        ],
      }),
    },
    {
      id: 'franchise-sunset-decision',
      category: 'finance',
      scope: 'studio',
      requiresArc: { id: 'franchise-fatigue', minStage: 2, status: 'active' },
      title: "The Franchise's Future",
      decisionTitle: "The Franchise's Future",
      body: 'The board wants a formal position: continue, reinvent, or close gracefully while goodwill remains.',
      cooldownWeeks: 14,
      baseWeight: 0.8,
      minWeek: 16,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        arcId: 'franchise-fatigue',
        arcStage: 2,
        title: "The Franchise's Future",
        body: 'This call locks the next cycle of capital allocation and brand posture.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Commit To A Final Theatrical Installment',
            preview: 'Costs money. Closes on earned terms.',
            cashDelta: -200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: 2,
            criticsDelta: 2,
            distributorRepDelta: 2,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Rebuild Theatrical Positioning',
            preview: 'Costs cash now to reset audience confidence in the next release cycle.',
            cashDelta: -140_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 2,
            audienceDelta: 2,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Announce The Franchise Is Complete',
            preview: 'No cash. Maximum goodwill exit.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 3,
            audienceDelta: 1,
            talentRepDelta: 1,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Continue Without A Plan',
            preview: 'The industry will make the decision for you.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: -3,
            criticsDelta: -2,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'returning-cast-negotiation',
      category: 'talent',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      requiresFlag: 'franchise_rights',
      title: 'Returning Cast Premium',
      decisionTitle: 'Returning Cast Premium',
      body: "A key returning cast member's new reps are demanding a premium package and credit upgrade.",
      cooldownWeeks: 6,
      baseWeight: 1.1,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Returning Cast Premium',
        body: `${projectTitle ?? 'The sequel'} depends on this role more than your legal leverage suggests.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Meet The Ask',
            preview: 'Earns loyalty. Expensive precedent.',
            cashDelta: -280_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            talentRepDelta: 2,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Counter At 60% Of The Ask',
            preview: 'Standard negotiation outcome. Actor is mildly unhappy.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: 1,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Recast The Role',
            preview: 'Curiosity bump. Audience trust takes a real hit.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: -2,
            audienceDelta: -3,
          },
        ],
      }),
    },
    {
      id: 'sequel-tracking-shock',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      requiresFlag: 'franchise_rights',
      title: 'Sequel Tracking Underperforms',
      decisionTitle: 'Sequel Tracking Underperforms',
      body: "Opening tracking lands well below the original's pre-release pace and exhibitor confidence softens.",
      cooldownWeeks: 8,
      baseWeight: 0.95,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Sequel Tracking Underperforms',
        body: `${projectTitle ?? 'The sequel'} needs a distribution response before bookings lock.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Emergency Paid Media Push',
            preview: 'Expensive. Moves the numbers.',
            cashDelta: -340_000,
            scriptQualityDelta: 0,
            hypeDelta: 4,
            audienceDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Lean Into Critical Early Reviews',
            preview: 'Cheaper repositioning. Works if reviews are strong.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            criticsDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Spend - Trust The Opening',
            preview: 'Saves money. Accepts the ceiling as-is.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'franchise-spinoff-pitch',
      category: 'creative',
      scope: 'studio',
      requiresFlag: 'franchise_committed',
      title: 'Spinoff Opportunity',
      decisionTitle: 'Spinoff Opportunity',
      body: 'A producer with expanded-universe credentials pitches a standalone spinoff around a supporting character.',
      cooldownWeeks: 14,
      baseWeight: 0.85,
      minWeek: 10,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'creative',
        title: 'Spinoff Opportunity',
        body: 'The proposal is credible but will compete with core-franchise resources.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Greenlight The Spinoff',
            preview: 'Expanded IP reach. Real overhead commitment.',
            cashDelta: -320_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: 1,
            audienceDelta: 2,
            setFlag: 'franchise_spinoff_active',
          },
          {
            id: idFactory('opt'),
            label: 'Option The Concept Only',
            preview: 'Cheap hold. Buys time without obligation.',
            cashDelta: -100_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Pass - Focus On Core Franchise',
            preview: 'Auteur signal. No distraction.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
          },
        ],
      }),
    },
    {
      id: 'legacy-anchor-departure',
      category: 'talent',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      requiresFlag: 'franchise_rights',
      title: 'Franchise Anchor Exit',
      decisionTitle: 'Franchise Anchor Exit',
      body: 'The actor most identified with the franchise signals they are ready to exit after this installment.',
      cooldownWeeks: 16,
      baseWeight: 0.8,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Franchise Anchor Exit',
        body: `${projectTitle ?? 'The current installment'} needs an immediate narrative strategy around cast continuity.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Co-Craft A Graceful Exit Narrative',
            preview: 'Industry goodwill. Audience gets closure.',
            cashDelta: -180_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 2,
            audienceDelta: 1,
            talentRepDelta: 2,
            setFlag: 'legacy_anchor_retired',
          },
          {
            id: idFactory('opt'),
            label: 'Pressure Them To Stay',
            preview: 'Buys one more installment. Costs the relationship.',
            cashDelta: -300_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: -2,
            audienceDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Say Nothing - Let Events Unfold',
            preview: 'The story will break on its own terms.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: -2,
            criticsDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'franchise-merch-window',
      category: 'finance',
      scope: 'studio',
      requiresFlag: 'franchise_committed',
      title: 'Merchandise Licensing Deal',
      decisionTitle: 'Merchandise Licensing Deal',
      body: 'A consumer products conglomerate offers a five-year licensing agreement across toys, apparel, and parks.',
      cooldownWeeks: 16,
      baseWeight: 0.9,
      minWeek: 8,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Merchandise Licensing Deal',
        body: 'The advance is meaningful, but long-tail brand control changes depending on exclusivity.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Sign Exclusive Deal',
            preview: 'Large upfront. Brand dilution risk is real.',
            cashDelta: 500_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: 2,
            criticsDelta: -1,
            setFlag: 'franchise_merch_deal',
          },
          {
            id: idFactory('opt'),
            label: 'Sign Non-Exclusive Deal',
            preview: 'Smaller advance. Retains flexibility.',
            cashDelta: 200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Pass - Protect Brand Integrity',
            preview: 'No revenue. Clean artistic signal.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
          },
        ],
      }),
    },
    {
      id: 'rival-counterprogramming',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      requiresFlag: 'franchise_rights',
      title: 'Rival Franchise Counterprogramming',
      decisionTitle: 'Rival Franchise Counterprogramming',
      body: 'A competing studio shifted its sequel into your launch corridor and your distributor wants a decision now.',
      cooldownWeeks: 8,
      baseWeight: 1.0,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Rival Franchise Counterprogramming',
        body: `${projectTitle ?? 'Your release'} now overlaps with a direct rival franchise opening.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Hold Date - Fight For Screens',
            preview: 'Spend to defend. Earns distributor respect.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            distributorRepDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Move One Week Earlier',
            preview: 'Modest cost. Gets clear field for a week.',
            cashDelta: -100_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            releaseWeekShift: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Move Two Weeks Later',
            preview: 'Cheapest option. Loses momentum.',
            cashDelta: -80_000,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            audienceDelta: -1,
            releaseWeekShift: 2,
          },
        ],
      }),
    },
    {
      id: 'sequel-director-leverage',
      category: 'talent',
      scope: 'project',
      targetPhases: ['preProduction'],
      requiresFlag: 'franchise_rights',
      title: 'Director Franchise Leverage',
      decisionTitle: 'Director Franchise Leverage',
      body: 'Your sequel director wants final cut, non-binding testing notes, and a guaranteed third-act budget floor.',
      cooldownWeeks: 10,
      baseWeight: 0.9,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Director Franchise Leverage',
        body: `${projectTitle ?? 'The sequel'} can concede terms for creative cohesion or reset leadership.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Grant All Three Conditions',
            preview: 'Director commits fully. Commercial ceiling narrows.',
            cashDelta: 0,
            scriptQualityDelta: 0.5,
            hypeDelta: 0,
            talentRepDelta: 3,
            criticsDelta: 3,
            overrunRiskDelta: -0.04,
            audienceDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Grant Creative But Not Budget Floor',
            preview: 'Compromise that leaves both sides mildly unsatisfied.',
            cashDelta: 0,
            scriptQualityDelta: 0.3,
            hypeDelta: 0,
            talentRepDelta: 1,
            criticsDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Deny All - Find A New Director',
            preview: 'New director announcement bump. Relationship cost is real.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            talentRepDelta: -3,
            criticsDelta: -2,
          },
        ],
      }),
    },
    {
      id: 'franchise-universe-pitch',
      category: 'finance',
      scope: 'studio',
      requiresFlag: 'franchise_committed',
      title: 'Global Roadshow Expansion',
      decisionTitle: 'Global Roadshow Expansion',
      body: 'An international distributor proposes a multi-territory roadshow campaign to expand theatrical reach for the franchise.',
      cooldownWeeks: 18,
      baseWeight: 0.75,
      minWeek: 12,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Global Roadshow Expansion',
        body: 'The deal increases theatrical footprint but locks campaign commitments across multiple regions.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund Full Roadshow',
            preview: 'Highest theatrical reach with real operating overhead.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 3,
            audienceDelta: 3,
            talentRepDelta: 1,
            setFlag: 'franchise_global_campaign',
          },
          {
            id: idFactory('opt'),
            label: 'Pilot Two Markets',
            preview: 'Moderate spend and focused regional upside.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: 1,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Decline - Protect Core Markets',
            preview: 'No expansion cost. Retains flexibility for future cycles.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 1,
            criticsDelta: 1,
          },
        ],
      }),
    },
];
