import type { EventTemplate } from '../types';

export const passionProjectEventDeck: EventTemplate[] = [
// ─── Phase 4: New Arc B — passion-project ────────────────────────────────

    {
      id: 'final-cut-rights-demand',
      category: 'creative',
      scope: 'project',
      targetPhases: ['preProduction'],
      blocksArc: { id: 'passion-project', status: 'resolved' },
      title: 'Final Cut Demand',
      decisionTitle: 'Final Cut Demand',
      body: 'Your director wants contractual final cut protection before committing to principal photography. No hedge. No override clause.',
      cooldownWeeks: 6,
      baseWeight: 0.95,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        arcId: 'passion-project',
        arcStage: 0,
        title: 'Final Cut Demand',
        body: projectTitle
          ? `The director on ${projectTitle} wants contractual final cut before principal photography begins.`
          : 'Your director wants contractual final cut protection before cameras roll.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Grant Final Cut',
            preview: 'Full creative latitude. Distributors will ask questions.',
            cashDelta: 0,
            scriptQualityDelta: 0.4,
            hypeDelta: 0,
            talentRepDelta: 2,
            distributorRepDelta: -1,
            setFlag: 'director_final_cut',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Offer Consulting Rights Only',
            preview: 'Partial compromise. Director may walk.',
            cashDelta: 0,
            scriptQualityDelta: 0.1,
            hypeDelta: 0,
            talentRepDelta: -1,
            failArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Studio Override',
            preview: 'Studio wins the argument. May lose the director.',
            cashDelta: 0,
            scriptQualityDelta: -0.2,
            hypeDelta: 0,
            talentRepDelta: -3,
            failArc: true,
          },
        ],
      }),
    },

    {
      id: 'genre-defying-dailies',
      category: 'creative',
      scope: 'project',
      targetPhases: ['production'],
      requiresArc: { id: 'passion-project', minStage: 1, status: 'active' },
      title: "The Dailies Don't Lie",
      decisionTitle: "The Dailies Don't Lie",
      body: "What's on screen is more experimental than the pitch deck suggested. The director is running with it. Audiences may not follow.",
      cooldownWeeks: 8,
      baseWeight: 1.0,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        arcId: 'passion-project',
        arcStage: 1,
        title: "The Dailies Don't Lie",
        body: projectTitle
          ? `${projectTitle} is heading somewhere more experimental than the pitch. Back the vision or ask for a safety net?`
          : "The film is heading somewhere more experimental than the pitch. Back the vision or ask for a safety net?",
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Back The Vision Fully',
            preview: 'Prestige upside. Commercial risk is real.',
            cashDelta: -180_000,
            scriptQualityDelta: 0.5,
            hypeDelta: 0,
            criticsDelta: 3,
            audienceDelta: -2,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Request A Commercial Scene Package',
            preview: 'Costs money to hedge. Gets safer and less distinctive.',
            cashDelta: -200_000,
            scriptQualityDelta: 0.2,
            hypeDelta: 0,
            criticsDelta: -1,
            audienceDelta: 2,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Trigger A Review Clause',
            preview: 'Studio overrides a protected director. Reputation damage across the industry.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: -3,
            criticsDelta: -2,
            setArcStage: 2,
          },
        ],
      }),
    },

    {
      id: 'critical-split-reception',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresArc: { id: 'passion-project', minStage: 2, status: 'active' },
      title: 'The Split',
      decisionTitle: 'The Split',
      body: "Festival darlings are calling it a masterwork. Major press is calling it inaccessible. Your distributor is watching the tracking numbers.",
      cooldownWeeks: 10,
      baseWeight: 0.95,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        arcId: 'passion-project',
        arcStage: 2,
        title: 'The Split',
        body: projectTitle
          ? `${projectTitle} has divided critics. Do you position for prestige or cut toward a mainstream audience?`
          : 'The film has divided critics. Position for prestige or cut toward a mainstream audience?',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Double Down On Prestige Positioning',
            preview: 'Premium awards-circuit positioning. Commercial ceiling is low.',
            cashDelta: -280_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 5,
            audienceDelta: -2,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Reposition For Mainstream',
            preview: 'Broader reach. Critics will notice the pivot.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -2,
            audienceDelta: 4,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: "Stay Out Of It — Let The Film Speak",
            preview: "Both camps notice you didn't choose. Momentum stalls.",
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
            audienceDelta: 1,
            failArc: true,
          },
        ],
      }),
    },
];
