import type { EventTemplate } from '../types';

export const standaloneEventDeck: EventTemplate[] = [
// ─── Phase 4: New Standalone Events ──────────────────────────────────────

    {
      id: 'emerging-talent-showcase',
      category: 'talent',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Breakout Performance',
      decisionTitle: 'Breakout Performance',
      body: 'Dailies show a supporting cast member delivering work well above their billing. Agents have already noticed.',
      cooldownWeeks: 5,
      baseWeight: 1.1,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Breakout Performance',
        body: projectTitle
          ? `A supporting actor on ${projectTitle} is outperforming their role. Agents have already noticed.`
          : 'A supporting actor is outperforming their role. Agents have already noticed.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Renegotiate Their Deal Now',
            preview: 'Costs now, earns loyalty and press.',
            cashDelta: -150_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            talentRepDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Flag For Press Positioning',
            preview: 'Free upside on campaign. No commitment.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            setFlag: 'breakout_talent',
          },
          {
            id: idFactory('opt'),
            label: 'Do Nothing',
            preview: "They'll remember.",
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'veteran-mentor-attachment',
      category: 'talent',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Veteran Mentor Offer',
      decisionTitle: 'Veteran Mentor Offer',
      body: 'A legendary filmmaker, now semi-retired, is available for a consulting credit. The name still carries weight in the room.',
      cooldownWeeks: 8,
      baseWeight: 0.9,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Veteran Mentor Offer',
        body: projectTitle
          ? `A legendary filmmaker is available to consult on ${projectTitle} for a credit and a fee.`
          : 'A legendary filmmaker is available for a consulting credit — for a fee.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Bring Them On',
            preview: 'Prestige signal. Costs more than it looks.',
            cashDelta: -180_000,
            scriptQualityDelta: 0.4,
            hypeDelta: 0,
            criticsDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Pass',
            preview: 'No cost, no gain.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },

    {
      id: 'union-action-warning',
      category: 'talent',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Union Warning',
      decisionTitle: 'Union Warning',
      body: 'A guild rep delivers a formal notice about overtime conditions in your production department. Not a threat yet. Noted.',
      cooldownWeeks: 4,
      baseWeight: 1.15,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Union Warning',
        body: projectTitle
          ? `Guild rep has issued a formal overtime notice on ${projectTitle}. Address it now or absorb the friction.`
          : 'Guild rep has issued a formal overtime notice. Address it now or absorb the friction.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Schedule A Rest Block',
            preview: 'Delays the shoot. Earns goodwill.',
            cashDelta: -200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            scheduleDelta: 1,
            talentRepDelta: 2,
            overrunRiskDelta: -0.04,
          },
          {
            id: idFactory('opt'),
            label: 'Negotiate A Quiet Settlement',
            preview: 'Faster and cheaper. Partial fix.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Continue Current Schedule',
            preview: 'Makes schedule. Will cost you at the next negotiating table.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            talentRepDelta: -2,
            overrunRiskDelta: 0.06,
          },
        ],
      }),
    },

    {
      id: 'breakout-casting-instinct',
      category: 'talent',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Unknown Lead Recommendation',
      decisionTitle: 'Unknown Lead Recommendation',
      body: 'Casting is pushing hard for a no-name lead. No agent, no track record. The audition tape is exceptional.',
      cooldownWeeks: 6,
      baseWeight: 0.95,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Unknown Lead Recommendation',
        body: projectTitle
          ? `Casting wants an unknown lead for ${projectTitle}. Exceptional audition, zero industry profile.`
          : 'Casting wants an unknown lead. Exceptional audition, zero industry profile.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Greenlight The Casting',
            preview: 'Critical upside. Opens the door for awards narrative.',
            cashDelta: 0,
            scriptQualityDelta: 0.2,
            hypeDelta: 0,
            criticsDelta: 2,
            audienceDelta: -1,
            setFlag: 'underdog_lead',
          },
          {
            id: idFactory('opt'),
            label: 'Go With The Safe Choice',
            preview: 'Audience-safe. Leaves prestige points on the table.',
            cashDelta: 0,
            scriptQualityDelta: -0.1,
            hypeDelta: 0,
            criticsDelta: -1,
            audienceDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'director-vision-clash',
      category: 'creative',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Director-DP Standoff',
      decisionTitle: 'Director-DP Standoff',
      body: 'Your director and cinematographer are deadlocked over visual approach three weeks into principal photography.',
      cooldownWeeks: 5,
      baseWeight: 1.1,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Director-DP Standoff',
        body: projectTitle
          ? `Director and DP on ${projectTitle} are at an impasse over visual language. Both have valid arguments.`
          : 'Director and DP are at an impasse over visual language. Both have valid arguments.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Back The Director',
            preview: 'Preserves creative coherence. Costs you a DP relationship.',
            cashDelta: 0,
            scriptQualityDelta: 0.2,
            hypeDelta: -1,
            talentRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Back The DP',
            preview: 'More commercial result. Director friction.',
            cashDelta: 0,
            scriptQualityDelta: -0.1,
            hypeDelta: 2,
            talentRepDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Bring In A Mediator',
            preview: 'Costs cash. Resolves cleanly.',
            cashDelta: -120_000,
            scriptQualityDelta: 0.1,
            hypeDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'cold-audience-test',
      category: 'creative',
      scope: 'project',
      targetPhases: ['postProduction'],
      title: 'Cold Read Returns',
      decisionTitle: 'Cold Read Returns',
      body: 'An unannounced civilian test screening returns scores that contradict your internal tracking.',
      cooldownWeeks: 5,
      baseWeight: 1.05,
      minWeek: 5,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Cold Read Returns',
        body: projectTitle
          ? `An unannounced civilian screening of ${projectTitle} returned unexpected scores. Internal tracking had it wrong.`
          : 'An unannounced civilian screening returned unexpected scores. Internal tracking had it wrong.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Order A Targeted Recut',
            preview: 'Costs money and time. Fixes the problem.',
            cashDelta: -230_000,
            scriptQualityDelta: 0.3,
            hypeDelta: 0,
          },
          {
            id: idFactory('opt'),
            label: 'Dismiss The Data',
            preview: 'Bold stance. May be right.',
            cashDelta: 0,
            scriptQualityDelta: -0.1,
            hypeDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Commission A Second Screening',
            preview: 'More data, more delay.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'viral-set-moment',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['production', 'postProduction'],
      title: 'Viral Set Leak',
      decisionTitle: 'Viral Set Leak',
      body: "An unplanned on-set moment was captured on a crew member's phone. It's spreading. You didn't plan this.",
      cooldownWeeks: 6,
      baseWeight: 1.0,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Viral Set Leak',
        body: projectTitle
          ? `An unplanned moment from ${projectTitle}'s set is spreading online. Your marketing team is watching the numbers climb.`
          : "An unplanned on-set moment is spreading online. Your marketing team is watching the numbers climb.",
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Own It — Release Official Version',
            preview: 'Maximum audience reach. Critics notice the engineered enthusiasm.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 5,
            criticsDelta: -1,
            audienceDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Issue Takedown',
            preview: 'Controlled brand. Costs goodwill.',
            cashDelta: -80_000,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            criticsDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Stay Quiet',
            preview: 'Organic spread. Limited upside.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'critic-embargo-request',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      title: 'Critics Guild Embargo Lift',
      decisionTitle: 'Critics Guild Embargo Lift',
      body: 'A respected critics bloc is requesting an early embargo lift to align with their awards calendar. Your current cut would have to hold up.',
      cooldownWeeks: 5,
      baseWeight: 0.95,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Critics Guild Embargo Lift',
        body: projectTitle
          ? `A critics bloc wants an early embargo lift on ${projectTitle} to align with their awards cycle.`
          : 'A critics bloc wants an early embargo lift to align with their awards cycle.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Lift For Qualifying Outlets',
            preview: "High reward if the film holds. High exposure if it doesn't.",
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            criticsDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Maintain Full Embargo',
            preview: "Standard call. Minor critics friction.",
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Advance Access To Select Critics',
            preview: 'Careful version. Costs a little, risks a little less.',
            cashDelta: -60_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'campaign-repositioning',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      title: 'Campaign Reposition Window',
      decisionTitle: 'Campaign Reposition Window',
      body: "Test audience data shows the campaign is emphasizing the wrong elements. A pivot is still possible before wide release.",
      cooldownWeeks: 6,
      baseWeight: 1.0,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Campaign Reposition Window',
        body: projectTitle
          ? `Campaign data for ${projectTitle} is pointing the wrong direction. There's still time to pivot before wide release.`
          : "Campaign data is pointing the wrong direction. There's still time to pivot before wide release.",
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Rebuild Around Emotional Hook',
            preview: 'Expensive. Broadens the tent.',
            cashDelta: -280_000,
            scriptQualityDelta: 0,
            hypeDelta: 4,
            audienceDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Lean Into Genre Signifiers',
            preview: 'Cheaper repositioning. Trades prestige for attendance.',
            cashDelta: -140_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            criticsDelta: -1,
            audienceDelta: 3,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Current Campaign',
            preview: 'Saves money. Accepts current ceiling.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },

    {
      id: 'first-look-term-sheet',
      category: 'talent',
      scope: 'studio',
      title: 'First-Look Term Sheet',
      decisionTitle: 'First-Look Term Sheet',
      body: 'A major agency is offering an exclusive first-look deal on new material — upfront cost, ongoing script access.',
      cooldownWeeks: 12,
      baseWeight: 0.85,
      minWeek: 5,
      buildDecision: ({ idFactory, currentWeek }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'talent',
        title: 'First-Look Term Sheet',
        body: 'A major agency is offering exclusive first-look rights on new writer and director packages. Upfront cost, long-term pipeline access.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Sign The Deal',
            preview: 'Better talent pipeline access. Costs independence.',
            cashDelta: -340_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            talentRepDelta: 2,
            setFlag: 'first_look_active',
          },
          {
            id: idFactory('opt'),
            label: 'Pass — Stay Open Market',
            preview: 'No upfront. Slight signal of self-reliance.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: -1,
            distributorRepDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'year-end-snub',
      category: 'marketing',
      scope: 'studio',
      title: 'Year-End Recognition Snub',
      decisionTitle: 'Year-End Recognition Snub',
      body: "A significant industry list omits your studio entirely. The gap between your output and the industry's perception of you is showing.",
      cooldownWeeks: 18,
      baseWeight: 0.8,
      minWeek: 8,
      buildDecision: ({ idFactory, currentWeek }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'marketing',
        title: 'Year-End Recognition Snub',
        body: "A major year-end industry list passed your studio over. The gap between your work and your reputation is public now.",
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Commission A Trade Campaign',
            preview: 'Costs money. Makes the case.',
            cashDelta: -200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 2,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Let The Work Speak',
            preview: 'No spend. Slightly better than nothing.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'acquisition-rumor',
      category: 'finance',
      scope: 'studio',
      blocksFlag: 'independence_declared',
      title: 'Acquisition Rumor',
      decisionTitle: 'Acquisition Rumor',
      body: 'Trade press is running a story that a major studio is interested in acquiring your catalog and key talent relationships.',
      cooldownWeeks: 15,
      baseWeight: 0.9,
      minWeek: 10,
      buildDecision: ({ idFactory, currentWeek }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Acquisition Rumor',
        body: "Trade press is running acquisition speculation. Your team is asking questions. How you respond sets the tone.",
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Issue A Strong Denial',
            preview: 'Reassures your people. Closes the story.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: 1,
            distributorRepDelta: 1,
            setFlag: 'independence_declared',
          },
          {
            id: idFactory('opt'),
            label: 'Stay Quiet',
            preview: 'Attention without commitment. Staff reads into it.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            talentRepDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Engage Exploratory Talks',
            preview: 'Pure profile play. Real internal cost.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: -2,
            audienceDelta: 2,
          },
        ],
      }),
    },

    {
      id: 'co-production-offer',
      category: 'finance',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Co-Production Offer',
      decisionTitle: 'Co-Production Offer',
      body: 'An international studio proposes co-production terms — shared cost, shared credit, and a required international location pivot.',
      cooldownWeeks: 7,
      baseWeight: 1.0,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Co-Production Offer',
        body: projectTitle
          ? `An international studio wants to co-produce ${projectTitle}. Shared cost, shared credit, mandatory location pivot.`
          : 'An international studio wants to co-produce. Shared cost, shared credit, mandatory location pivot.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Co-Production Terms',
            preview: 'Risk-sharing at the cost of creative control and timeline.',
            cashDelta: 380_000,
            scriptQualityDelta: -0.2,
            hypeDelta: -1,
            scheduleDelta: 1,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Counter With Equity-Only Terms',
            preview: 'Smaller cash. Keeps creative authority.',
            cashDelta: 180_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Decline',
            preview: 'Clean. No cash.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },

    {
      id: 'completion-bond-audit',
      category: 'finance',
      scope: 'project',
      targetPhases: ['production', 'postProduction'],
      title: 'Completion Bond Audit',
      decisionTitle: 'Completion Bond Audit',
      body: 'Bond underwriters request a compliance review before they keep covering late-stage risk.',
      cooldownWeeks: 12,
      baseWeight: 0.72,
      minWeek: 10,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Completion Bond Audit',
        body: projectTitle
          ? `Underwriters want a fast audit pass on ${projectTitle} before they confirm full completion coverage.`
          : 'Underwriters want a fast audit pass before they confirm full completion coverage.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Open Full Books',
            preview: 'Most expensive. Buys strongest confidence.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
            distributorRepDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Negotiate Limited Access',
            preview: 'Middle path with minor process drag.',
            cashDelta: -60_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 1,
            scheduleDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Refuse The Audit',
            preview: 'No cost now. Relationship damage later.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            distributorRepDelta: -2,
            audienceDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'crew-retention-bonus',
      category: 'operations',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      title: 'Crew Retention Bonus Pool',
      decisionTitle: 'Crew Retention Bonus Pool',
      body: 'Department heads warn that fatigue is rising and senior crew could walk before lock.',
      cooldownWeeks: 11,
      baseWeight: 0.78,
      minWeek: 10,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Crew Retention Bonus Pool',
        body: projectTitle
          ? `${projectTitle} is at risk of losing key crew unless retention terms improve this week.`
          : 'Key crew may leave unless retention terms improve this week.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund Full Bonus Pool',
            preview: 'Stabilizes set morale and keeps pace.',
            cashDelta: -220_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            talentRepDelta: 2,
            audienceDelta: 1,
            scheduleDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Cover Key Departments Only',
            preview: 'Cheaper partial solution.',
            cashDelta: -110_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            talentRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Current Terms',
            preview: 'No cash outlay. Turnover risk rises.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            talentRepDelta: -2,
            scheduleDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'third-act-clarity-pass',
      category: 'creative',
      scope: 'project',
      targetPhases: ['postProduction'],
      title: 'Third Act Clarity Pass',
      decisionTitle: 'Third Act Clarity Pass',
      body: 'Late cuts reveal confusion in the final act. There is still time for a targeted fix.',
      cooldownWeeks: 12,
      baseWeight: 0.7,
      minWeek: 11,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Third Act Clarity Pass',
        body: projectTitle
          ? `${projectTitle} can run a late clarity pass to tighten the ending before final lock.`
          : 'You can run a late clarity pass to tighten the ending before final lock.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Run Pickup And Rewrite Pass',
            preview: 'High-cost repair with strongest upside.',
            cashDelta: -260_000,
            scriptQualityDelta: 0.3,
            hypeDelta: 0,
            criticsDelta: 2,
            scheduleDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'ADR And Edit Tightening',
            preview: 'Moderate improvement for lower spend.',
            cashDelta: -90_000,
            scriptQualityDelta: 0.1,
            hypeDelta: 0,
            criticsDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Ship Current Cut',
            preview: 'Protect schedule and cash.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'industry-analyst-day',
      category: 'marketing',
      scope: 'studio',
      title: 'Industry Analyst Day',
      decisionTitle: 'Industry Analyst Day',
      body: 'Trade analysts ask for direct studio briefings on your slate quality and long-term strategy.',
      cooldownWeeks: 20,
      baseWeight: 0.66,
      minWeek: 16,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'marketing',
        title: 'Industry Analyst Day',
        body: 'How you present the slate this quarter will shape distributor confidence for upcoming negotiations.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Host Full Showcase',
            preview: 'Costs cash. Builds broad confidence.',
            cashDelta: -190_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            distributorRepDelta: 2,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Run Private Briefings',
            preview: 'Cheaper and focused.',
            cashDelta: -70_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Skip This Cycle',
            preview: 'No spend. Leaves narrative to others.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
            distributorRepDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'guild-training-initiative',
      category: 'operations',
      scope: 'studio',
      title: 'Guild Training Initiative',
      decisionTitle: 'Guild Training Initiative',
      body: 'Guild reps invite the studio to co-fund a new below-the-line training pipeline.',
      cooldownWeeks: 26,
      baseWeight: 0.6,
      minWeek: 20,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'operations',
        title: 'Guild Training Initiative',
        body: 'It is not mandatory, but the industry will remember who helped staff the next generation.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Sponsor At Lead Tier',
            preview: 'Strong long-term goodwill play.',
            cashDelta: -240_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
            talentRepDelta: 3,
          },
          {
            id: idFactory('opt'),
            label: 'Join As Co-Funder',
            preview: 'Balanced contribution.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: 1,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Decline Participation',
            preview: 'Save cash now. Creates labor friction.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            talentRepDelta: -2,
            audienceDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'release-calendar-jam',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      title: 'Release Calendar Jam',
      decisionTitle: 'Release Calendar Jam',
      body: 'Two similar titles moved into your corridor and exhibitors are signaling tighter screen access.',
      cooldownWeeks: 13,
      baseWeight: 0.76,
      minWeek: 14,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Release Calendar Jam',
        body: projectTitle
          ? `${projectTitle} now shares a crowded window and your booking leverage is being tested.`
          : 'Your release now shares a crowded window and booking leverage is being tested.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Buy Premium Screens',
            preview: 'Expensive defense, keeps pressure on rivals.',
            cashDelta: -300_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            distributorRepDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Shift One Week',
            preview: 'Moderate cost, cleaner lane.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            audienceDelta: 1,
            releaseWeekShift: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Current Plan',
            preview: 'No spend, weaker leverage.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            distributorRepDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'library-restoration-package',
      category: 'finance',
      scope: 'studio',
      title: 'Library Restoration Package',
      decisionTitle: 'Library Restoration Package',
      body: 'A restoration vendor offers a discounted package to remaster catalog titles and relaunch them in premium formats.',
      cooldownWeeks: 30,
      baseWeight: 0.55,
      minWeek: 22,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Library Restoration Package',
        body: 'Catalog strategy will not move this quarter cash flow, but it can change how the studio is valued long-term.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Restore Full Catalog Set',
            preview: 'Largest cost, strongest legacy signal.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 2,
            audienceDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Restore Select Titles',
            preview: 'Moderate spend, moderate upside.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 1,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Pass This Cycle',
            preview: 'No cost now.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'festival-jury-lobby-window',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      title: 'Festival Jury Lobby Window',
      decisionTitle: 'Festival Jury Lobby Window',
      body: 'Publicists present a narrow outreach window to shape early festival juror sentiment.',
      cooldownWeeks: 14,
      baseWeight: 0.68,
      minWeek: 12,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Festival Jury Lobby Window',
        body: projectTitle
          ? `Publicists believe ${projectTitle} can gain festival leverage with immediate targeted outreach.`
          : 'Publicists believe this title can gain festival leverage with immediate targeted outreach.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Run Full Outreach Push',
            preview: 'Highest influence, highest spend.',
            cashDelta: -150_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 2,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Keep It Low-Key',
            preview: 'Lower spend, controlled upside.',
            cashDelta: -60_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Avoid Lobbying',
            preview: 'No spend, no narrative control.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
            talentRepDelta: 1,
          },
        ],
      }),
    },
];
