import type { EventTemplate } from './types';

export function getEventDeck(): EventTemplate[] {
  return [
    {
      id: 'rewrite-window',
      category: 'creative',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Rewrite Window',
      decisionTitle: 'Rewrite Pass Opportunity',
      body: 'A top script doctor opens a one-week slot.',
      cooldownWeeks: 3,
      baseWeight: 1.4,
      minWeek: 1,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Rewrite Pass Opportunity',
        body: `${projectTitle ?? 'A project'} can book a premium rewrite pass this week only.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Approve Rewrite',
            preview: 'Script quality improves and development confidence rises.',
            cashDelta: -140_000,
            scriptQualityDelta: 0.6,
            hypeDelta: 1,
            setFlag: 'rewrite_invested',
          },
          {
            id: idFactory('opt'),
            label: 'Decline',
            preview: 'Save cash and move on with current pages.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'financier-notes',
      category: 'finance',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Financier Notes Pass',
      decisionTitle: 'Financier Notes Request',
      body: 'A co-financier offers cash now in exchange for script notes and control.',
      cooldownWeeks: 4,
      baseWeight: 1,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Financier Notes Request',
        body: `${projectTitle ?? 'The project'} can secure early money if you accept commercial notes.`,
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Take The Cash',
            preview: 'Immediate runway boost, but creative compromise.',
            cashDelta: 220_000,
            scriptQualityDelta: -0.4,
            hypeDelta: -1,
            studioHeatDelta: -1,
            setFlag: 'financier_control',
          },
          {
            id: idFactory('opt'),
            label: 'Hold Creative Line',
            preview: 'No cash injection, but your brand strength improves.',
            cashDelta: 0,
            scriptQualityDelta: 0.1,
            hypeDelta: 1,
            studioHeatDelta: 1,
            clearFlag: 'financier_control',
          },
        ],
      }),
    },
    {
      id: 'table-read-breakthrough',
      category: 'creative',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Table Read Breakthrough',
      decisionTitle: 'Table Read Discovery',
      body: 'A table read reveals a stronger emotional direction.',
      cooldownWeeks: 5,
      baseWeight: 1.1,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Table Read Discovery',
        body: `${projectTitle ?? 'The script'} has a chance to improve with one focused polish sprint.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund A Polish Sprint',
            preview: 'Sharper pages and stronger cast confidence.',
            cashDelta: -180_000,
            scriptQualityDelta: 0.4,
            hypeDelta: 2,
            studioHeatDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Lock Current Draft',
            preview: 'No new spend, but less momentum at this stage.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'tax-credit-window',
      category: 'finance',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      title: 'Tax Credit Window',
      decisionTitle: 'Regional Tax Credit Offer',
      body: 'A region opens a short-lived incentive program with strict timing.',
      cooldownWeeks: 4,
      baseWeight: 1.15,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Regional Tax Credit Offer',
        body: `${projectTitle ?? 'The production'} can qualify if logistics move now.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Relocate Unit',
            preview: 'Front-load spend to reduce long-tail schedule and risk.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            scheduleDelta: -1,
            overrunRiskDelta: -0.08,
          },
          {
            id: idFactory('opt'),
            label: 'Stay Put',
            preview: 'Keep production stable and avoid relocation churn.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
    {
      id: 'crew-morale-check',
      category: 'operations',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Crew Morale Warning',
      decisionTitle: 'Crew Morale Intervention',
      body: 'Line producers report burnout risk across key departments.',
      cooldownWeeks: 3,
      baseWeight: 1.2,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Crew Morale Intervention',
        body: `${projectTitle ?? 'This production'} is showing fatigue indicators.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Add Relief Crew',
            preview: 'Costly now, but stabilizes execution and press sentiment.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            studioHeatDelta: 1,
            overrunRiskDelta: -0.05,
          },
          {
            id: idFactory('opt'),
            label: 'Push Through',
            preview: 'Stay on spend, but pressure and overrun risk increase.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            scheduleDelta: -1,
            overrunRiskDelta: 0.06,
          },
        ],
      }),
    },
    {
      id: 'practical-stunt-package',
      category: 'operations',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Practical Stunt Package',
      decisionTitle: 'Practical Stunt Upgrade',
      body: 'A top stunt team can execute a real sequence the VFX route cannot match.',
      cooldownWeeks: 5,
      baseWeight: 1.05,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Practical Stunt Upgrade',
        body: `${projectTitle ?? 'The production'} can pivot toward a practical centerpiece shot.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Greenlight Practical Unit',
            preview: 'Bigger buzz and authenticity, but heavier execution risk.',
            cashDelta: -320_000,
            scriptQualityDelta: 0,
            hypeDelta: 5,
            overrunRiskDelta: 0.04,
          },
          {
            id: idFactory('opt'),
            label: 'Stay VFX-Heavy',
            preview: 'Safer operating profile with a smaller hype upside.',
            cashDelta: -80_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            overrunRiskDelta: -0.02,
          },
        ],
      }),
    },
    {
      id: 'post-pipeline-upgrade',
      category: 'operations',
      scope: 'project',
      targetPhases: ['postProduction'],
      title: 'Post Pipeline Upgrade',
      decisionTitle: 'Post Pipeline Decision',
      body: 'Editorial can move to a faster pipeline this week with vendor support.',
      cooldownWeeks: 4,
      baseWeight: 1.05,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Post Pipeline Decision',
        body: `${projectTitle ?? 'Post'} can lock picture faster with outside support.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Buy Vendor Upgrade',
            preview: 'Reduce delay risk and tighten release readiness.',
            cashDelta: -240_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            scheduleDelta: -1,
            overrunRiskDelta: -0.05,
          },
          {
            id: idFactory('opt'),
            label: 'Keep Current Pipeline',
            preview: 'No spend now, but timeline remains fragile.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'leaked-rough-cut',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      blocksFlag: 'security_hardened',
      title: 'Rough Cut Leak',
      decisionTitle: 'Leak Response Plan',
      body: 'A low-quality clip spread online before marketing was ready.',
      cooldownWeeks: 6,
      baseWeight: 0.95,
      minWeek: 5,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Leak Response Plan',
        body: `${projectTitle ?? 'A project'} leaked early. The response will shape audience narrative.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Forensic Takedown + Silence',
            preview: 'Contain damage at cost and stabilize reputation.',
            cashDelta: -210_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            studioHeatDelta: 1,
            setFlag: 'security_hardened',
            clearFlag: 'security_breach',
          },
          {
            id: idFactory('opt'),
            label: 'Ignore And Move On',
            preview: 'No spend, but uncontrolled chatter can snowball.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -4,
            studioHeatDelta: -2,
            setFlag: 'security_breach',
          },
          {
            id: idFactory('opt'),
            label: 'Counter With Official Teaser',
            preview: 'Spend modestly to reset narrative with an approved cut.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            setFlag: 'security_breach',
          },
        ],
      }),
    },
    {
      id: 'anti-piracy-sweep',
      category: 'operations',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresFlag: 'security_breach',
      title: 'Piracy Fallout',
      decisionTitle: 'Piracy Countermeasure',
      body: 'Leak chatter converted into early piracy copies in two territories.',
      cooldownWeeks: 6,
      baseWeight: 1.2,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Piracy Countermeasure',
        body: `${projectTitle ?? 'The title'} needs a response before momentum erodes further.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Launch Legal Blitz',
            preview: 'Contain losses with direct legal pressure.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            clearFlag: 'security_breach',
            setFlag: 'security_hardened',
          },
          {
            id: idFactory('opt'),
            label: 'Own The Narrative',
            preview: 'Spend on communication and fan conversion.',
            cashDelta: -60_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 1,
            clearFlag: 'security_breach',
          },
          {
            id: idFactory('opt'),
            label: 'Ride It Out',
            preview: 'Protect cash but absorb measurable momentum loss.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -3,
            studioHeatDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'festival-slot',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      title: 'Festival Programming Slot',
      decisionTitle: 'Festival Slot Offer',
      body: 'A mid-tier festival programmer offers an early slot.',
      cooldownWeeks: 4,
      baseWeight: 1.1,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Festival Slot Offer',
        body: `${projectTitle ?? 'The title'} can take a festival slot and signal prestige early.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Submit Festival Cut',
            preview: 'Potential critic momentum with moderate spend.',
            cashDelta: -200_000,
            scriptQualityDelta: 0,
            hypeDelta: 4,
            studioHeatDelta: 2,
            setFlag: 'festival_selected',
          },
          {
            id: idFactory('opt'),
            label: 'Skip Festival Route',
            preview: 'Keep launch control and cash for later windows.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'awards-whisper-campaign',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresFlag: 'festival_selected',
      title: 'Awards Whisper Campaign',
      decisionTitle: 'Awards Campaign Decision',
      body: 'Publicists believe the title has enough momentum for a real awards push.',
      cooldownWeeks: 8,
      baseWeight: 0.9,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Awards Campaign Decision',
        body: `${projectTitle ?? 'The release'} can escalate to a full awards campaign.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund Campaign',
            preview: 'Higher profile and long-tail brand upside.',
            cashDelta: -280_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 4,
            setFlag: 'awards_campaign',
          },
          {
            id: idFactory('opt'),
            label: 'Stay Disciplined',
            preview: 'Save cash and avoid prestige spend creep.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'premium-trailer-placement',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      title: 'Trailer Slot',
      decisionTitle: 'Premium Trailer Placement',
      body: 'A distributor opens premium trailer placement for a short window.',
      cooldownWeeks: 4,
      baseWeight: 1.1,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Premium Trailer Placement',
        body: `${projectTitle ?? 'The title'} can buy premium placement now or hold spend for later.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Buy Placement',
            preview: 'Higher awareness and stronger opening readiness.',
            cashDelta: -330_000,
            scriptQualityDelta: 0,
            hypeDelta: 6,
            marketingDelta: 250_000,
          },
          {
            id: idFactory('opt'),
            label: 'Pass',
            preview: 'Keep powder dry for a later marketing burst.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
    {
      id: 'brand-integration-deal',
      category: 'finance',
      scope: 'project',
      targetPhases: ['production', 'distribution'],
      title: 'Brand Integration Offer',
      decisionTitle: 'Brand Integration Deal',
      body: 'A consumer brand offers placement money with approval rights.',
      cooldownWeeks: 5,
      baseWeight: 1,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Brand Integration Deal',
        body: `${projectTitle ?? 'The project'} can lock an integration package this week.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Take The Deal',
            preview: 'Improves cash, but creative perception softens slightly.',
            cashDelta: 450_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: -1,
            setFlag: 'brand_partner',
          },
          {
            id: idFactory('opt'),
            label: 'Decline',
            preview: 'No new money, but preserves brand identity.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: 1,
          },
        ],
      }),
    },
    {
      id: 'bridge-financing',
      category: 'finance',
      scope: 'studio',
      title: 'Bridge Financing Offer',
      decisionTitle: 'Bridge Financing Term Sheet',
      body: 'A lender offers a short facility to smooth production cashflow.',
      cooldownWeeks: 7,
      baseWeight: 0.9,
      minWeek: 2,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Bridge Financing Term Sheet',
        body: 'The facility gives breathing room now but can hurt your heat if overused.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Draw Facility',
            preview: 'Immediate cash cushion at reputation cost.',
            cashDelta: 1_200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: -2,
            setFlag: 'bridge_debt',
          },
          {
            id: idFactory('opt'),
            label: 'Stay Lean',
            preview: 'No debt draw and stronger market discipline signal.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 1,
            clearFlag: 'bridge_debt',
          },
        ],
      }),
    },
    {
      id: 'agency-package-push',
      category: 'talent',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Agency Package Push',
      decisionTitle: 'Agency Packaging Proposal',
      body: 'A major agency offers a packaged talent bundle with a short deadline.',
      cooldownWeeks: 5,
      baseWeight: 0.95,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Agency Packaging Proposal',
        body: `${projectTitle ?? 'The project'} can move faster if you accept packaged attachments.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Package Terms',
            preview: 'Faster schedule and buzz, with a meaningful upfront cost.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            scheduleDelta: -1,
            studioHeatDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Run Open Market',
            preview: 'Keep flexibility and preserve cash.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
  ];
}
