import type { EventTemplate } from './types';

export function getEventDeck(): EventTemplate[] {
  return [
    {
      id: 'rewrite-window',
      category: 'creative',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Rewrite Window',
      decisionTitle: 'Rewrite Pass Opportunity',
      body: 'A top script doctor opens a one-week slot.',
      cooldownWeeks: 3,
      baseWeight: 1.4,
      minWeek: 1,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Rewrite Pass Opportunity',
        body: `${projectTitle ?? 'A project'} can book a premium rewrite pass this week only.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Approve Rewrite',
            preview: 'Script quality improves and development confidence rises.',
            cashDelta: -140_000,
            scriptQualityDelta: 0.6,
            hypeDelta: 1,
            setFlag: 'rewrite_invested',
          },
          {
            id: idFactory('opt'),
            label: 'Decline',
            preview: 'Save cash and move on with current pages.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'financier-notes',
      category: 'finance',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      blocksArc: { id: 'financier-control', status: 'resolved' },
      title: 'Financier Notes Pass',
      decisionTitle: 'Financier Notes Request',
      body: 'A co-financier offers cash now in exchange for script notes and control.',
      cooldownWeeks: 4,
      baseWeight: 1,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'financier-control',
        arcStage: 0,
        title: 'Financier Notes Request',
        body: `${projectTitle ?? 'The project'} can secure early money if you accept commercial notes.`,
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Take The Cash',
            preview: 'Immediate runway boost, but creative compromise.',
            cashDelta: 220_000,
            scriptQualityDelta: -0.4,
            hypeDelta: -1,
            studioHeatDelta: -1,
            setFlag: 'financier_control',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Creative Line',
            preview: 'No cash injection, but your brand strength improves.',
            cashDelta: 0,
            scriptQualityDelta: 0.1,
            hypeDelta: 1,
            studioHeatDelta: 1,
            clearFlag: 'financier_control',
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'table-read-breakthrough',
      category: 'creative',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Table Read Breakthrough',
      decisionTitle: 'Table Read Discovery',
      body: 'A table read reveals a stronger emotional direction.',
      cooldownWeeks: 5,
      baseWeight: 1.1,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Table Read Discovery',
        body: `${projectTitle ?? 'The script'} has a chance to improve with one focused polish sprint.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund A Polish Sprint',
            preview: 'Sharper pages and stronger cast confidence.',
            cashDelta: -180_000,
            scriptQualityDelta: 0.4,
            hypeDelta: 2,
            studioHeatDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Lock Current Draft',
            preview: 'No new spend, but less momentum at this stage.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'financier-mandate-rewrite',
      category: 'finance',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      requiresArc: { id: 'financier-control', minStage: 1, status: 'active' },
      title: 'Financier Mandate Rewrite',
      decisionTitle: 'Mandatory Financier Changes',
      body: 'The financing partner now demands scene and casting adjustments mid-process.',
      cooldownWeeks: 6,
      baseWeight: 1.1,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'financier-control',
        arcStage: 1,
        title: 'Mandatory Financier Changes',
        body: `${projectTitle ?? 'The project'} must decide whether to accept deeper mandate clauses.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Mandate',
            preview: 'Secure added cash but sacrifice quality and autonomy.',
            cashDelta: 380_000,
            scriptQualityDelta: -0.5,
            hypeDelta: -2,
            studioHeatDelta: -2,
            setArcStage: 2,
            setFlag: 'financier_control',
          },
          {
            id: idFactory('opt'),
            label: 'Buy Out Clause',
            preview: 'Pay to regain control and restore creative momentum.',
            cashDelta: -420_000,
            scriptQualityDelta: 0.3,
            hypeDelta: 2,
            studioHeatDelta: 2,
            clearFlag: 'financier_control',
            resolveArc: true,
          },
        ],
      }),
    },
    {
      id: 'financier-test-screening-fallout',
      category: 'creative',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      requiresArc: { id: 'financier-control', minStage: 2, status: 'active' },
      title: 'Financier Cut Fallout',
      decisionTitle: 'Test Screening Damage Control',
      body: 'Audience scores crater after the mandated cut strategy leaks to press.',
      cooldownWeeks: 7,
      baseWeight: 1,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        arcId: 'financier-control',
        arcStage: 2,
        title: 'Test Screening Damage Control',
        body: `${projectTitle ?? 'The title'} can attempt a late recovery edit before release.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Re-cut For Cohesion',
            preview: 'Expensive rescue pass with upside on quality and heat.',
            cashDelta: -360_000,
            scriptQualityDelta: 0.5,
            hypeDelta: 2,
            studioHeatDelta: 2,
            clearFlag: 'financier_control',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Ship As Is',
            preview: 'Protect cash now but absorb long-tail brand damage.',
            cashDelta: 0,
            scriptQualityDelta: -0.2,
            hypeDelta: -3,
            studioHeatDelta: -3,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'tax-credit-window',
      category: 'finance',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      title: 'Tax Credit Window',
      decisionTitle: 'Regional Tax Credit Offer',
      body: 'A region opens a short-lived incentive program with strict timing.',
      cooldownWeeks: 4,
      baseWeight: 1.15,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Regional Tax Credit Offer',
        body: `${projectTitle ?? 'The production'} can qualify if logistics move now.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Relocate Unit',
            preview: 'Front-load spend to reduce long-tail schedule and risk.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            scheduleDelta: -1,
            overrunRiskDelta: -0.08,
          },
          {
            id: idFactory('opt'),
            label: 'Stay Put',
            preview: 'Keep production stable and avoid relocation churn.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
    {
      id: 'crew-morale-check',
      category: 'operations',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Crew Morale Warning',
      decisionTitle: 'Crew Morale Intervention',
      body: 'Line producers report burnout risk across key departments.',
      cooldownWeeks: 3,
      baseWeight: 1.2,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Crew Morale Intervention',
        body: `${projectTitle ?? 'This production'} is showing fatigue indicators.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Add Relief Crew',
            preview: 'Costly now, but stabilizes execution and press sentiment.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            studioHeatDelta: 1,
            overrunRiskDelta: -0.05,
          },
          {
            id: idFactory('opt'),
            label: 'Push Through',
            preview: 'Stay on spend, but pressure and overrun risk increase.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            scheduleDelta: -1,
            overrunRiskDelta: 0.06,
          },
        ],
      }),
    },
    {
      id: 'practical-stunt-package',
      category: 'operations',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Practical Stunt Package',
      decisionTitle: 'Practical Stunt Upgrade',
      body: 'A top stunt team can execute a real sequence the VFX route cannot match.',
      cooldownWeeks: 5,
      baseWeight: 1.05,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Practical Stunt Upgrade',
        body: `${projectTitle ?? 'The production'} can pivot toward a practical centerpiece shot.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Greenlight Practical Unit',
            preview: 'Bigger buzz and authenticity, but heavier execution risk.',
            cashDelta: -320_000,
            scriptQualityDelta: 0,
            hypeDelta: 5,
            overrunRiskDelta: 0.04,
          },
          {
            id: idFactory('opt'),
            label: 'Stay VFX-Heavy',
            preview: 'Safer operating profile with a smaller hype upside.',
            cashDelta: -80_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            overrunRiskDelta: -0.02,
          },
        ],
      }),
    },
    {
      id: 'post-pipeline-upgrade',
      category: 'operations',
      scope: 'project',
      targetPhases: ['postProduction'],
      title: 'Post Pipeline Upgrade',
      decisionTitle: 'Post Pipeline Decision',
      body: 'Editorial can move to a faster pipeline this week with vendor support.',
      cooldownWeeks: 4,
      baseWeight: 1.05,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Post Pipeline Decision',
        body: `${projectTitle ?? 'Post'} can lock picture faster with outside support.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Buy Vendor Upgrade',
            preview: 'Reduce delay risk and tighten release readiness.',
            cashDelta: -240_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            scheduleDelta: -1,
            overrunRiskDelta: -0.05,
          },
          {
            id: idFactory('opt'),
            label: 'Keep Current Pipeline',
            preview: 'No spend now, but timeline remains fragile.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'leaked-rough-cut',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      blocksFlag: 'security_hardened',
      blocksArc: { id: 'leak-piracy', status: 'resolved' },
      title: 'Rough Cut Leak',
      decisionTitle: 'Leak Response Plan',
      body: 'A low-quality clip spread online before marketing was ready.',
      cooldownWeeks: 6,
      baseWeight: 0.95,
      minWeek: 5,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        arcId: 'leak-piracy',
        arcStage: 0,
        title: 'Leak Response Plan',
        body: `${projectTitle ?? 'A project'} leaked early. The response will shape audience narrative.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Forensic Takedown + Silence',
            preview: 'Contain damage at cost and stabilize reputation.',
            cashDelta: -210_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            studioHeatDelta: 1,
            setFlag: 'security_hardened',
            clearFlag: 'security_breach',
            failArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Ignore And Move On',
            preview: 'No spend, but uncontrolled chatter can snowball.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -4,
            studioHeatDelta: -2,
            setFlag: 'security_breach',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Counter With Official Teaser',
            preview: 'Spend modestly to reset narrative with an approved cut.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            setFlag: 'security_breach',
            setArcStage: 1,
          },
        ],
      }),
    },
    {
      id: 'anti-piracy-sweep',
      category: 'operations',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresFlag: 'security_breach',
      requiresArc: { id: 'leak-piracy', minStage: 1, status: 'active' },
      title: 'Piracy Fallout',
      decisionTitle: 'Piracy Countermeasure',
      body: 'Leak chatter converted into early piracy copies in two territories.',
      cooldownWeeks: 6,
      baseWeight: 1.2,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        arcId: 'leak-piracy',
        arcStage: 1,
        title: 'Piracy Countermeasure',
        body: `${projectTitle ?? 'The title'} needs a response before momentum erodes further.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Launch Legal Blitz',
            preview: 'Contain losses with direct legal pressure.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            clearFlag: 'security_breach',
            setFlag: 'security_hardened',
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Own The Narrative',
            preview: 'Spend on communication and fan conversion.',
            cashDelta: -60_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 1,
            clearFlag: 'security_breach',
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Ride It Out',
            preview: 'Protect cash but absorb measurable momentum loss.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -3,
            studioHeatDelta: -1,
            advanceArcBy: 1,
          },
        ],
      }),
    },
    {
      id: 'exhibitor-trust-audit',
      category: 'operations',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresArc: { id: 'leak-piracy', minStage: 2, status: 'active' },
      title: 'Exhibitor Trust Audit',
      decisionTitle: 'Exhibitor Confidence Review',
      body: 'Major exhibitors request anti-piracy assurances before premium placement.',
      cooldownWeeks: 7,
      baseWeight: 1.05,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        arcId: 'leak-piracy',
        arcStage: 2,
        title: 'Exhibitor Confidence Review',
        body: `${projectTitle ?? 'The release'} can regain trust now or accept reduced screen quality.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund Security Audit',
            preview: 'Costly compliance, but stabilizes relationship and closes the arc.',
            cashDelta: -190_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            setFlag: 'security_hardened',
            clearFlag: 'security_breach',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Accept Reduced Placement',
            preview: 'Save cash immediately but lock in weaker release momentum.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            studioHeatDelta: -2,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'festival-slot',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      blocksArc: { id: 'awards-circuit', status: 'resolved' },
      title: 'Festival Programming Slot',
      decisionTitle: 'Festival Slot Offer',
      body: 'A mid-tier festival programmer offers an early slot.',
      cooldownWeeks: 4,
      baseWeight: 1.1,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        arcId: 'awards-circuit',
        arcStage: 0,
        title: 'Festival Slot Offer',
        body: `${projectTitle ?? 'The title'} can take a festival slot and signal prestige early.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Submit Festival Cut',
            preview: 'Potential critic momentum with moderate spend.',
            cashDelta: -200_000,
            scriptQualityDelta: 0,
            hypeDelta: 4,
            studioHeatDelta: 2,
            setFlag: 'festival_selected',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Skip Festival Route',
            preview: 'Keep launch control and cash for later windows.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'awards-whisper-campaign',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresFlag: 'festival_selected',
      requiresArc: { id: 'awards-circuit', minStage: 1, status: 'active' },
      title: 'Awards Whisper Campaign',
      decisionTitle: 'Awards Campaign Decision',
      body: 'Publicists believe the title has enough momentum for a real awards push.',
      cooldownWeeks: 8,
      baseWeight: 0.9,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        arcId: 'awards-circuit',
        arcStage: 1,
        title: 'Awards Campaign Decision',
        body: `${projectTitle ?? 'The release'} can escalate to a full awards campaign.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund Campaign',
            preview: 'Higher profile and long-tail brand upside.',
            cashDelta: -280_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 4,
            setFlag: 'awards_campaign',
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Stay Disciplined',
            preview: 'Save cash and avoid prestige spend creep.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: -1,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'guild-screening-crunch',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['released'],
      requiresArc: { id: 'awards-circuit', minStage: 2, status: 'active' },
      title: 'Guild Screening Crunch',
      decisionTitle: 'Guild Screening Emergency',
      body: 'Guild screenings underperformed and campaign momentum is fading.',
      cooldownWeeks: 8,
      baseWeight: 0.95,
      minWeek: 9,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        arcId: 'awards-circuit',
        arcStage: 2,
        title: 'Guild Screening Emergency',
        body: `${projectTitle ?? 'The awards title'} can mount a final rescue push this week.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Host Targeted Q&A Run',
            preview: 'Spend to regain credibility and potentially close the loop positively.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 3,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Wind Down Campaign',
            preview: 'Cut losses and accept a muted awards finish.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            studioHeatDelta: -2,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'premium-trailer-placement',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      title: 'Trailer Slot',
      decisionTitle: 'Premium Trailer Placement',
      body: 'A distributor opens premium trailer placement for a short window.',
      cooldownWeeks: 4,
      baseWeight: 1.1,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Premium Trailer Placement',
        body: `${projectTitle ?? 'The title'} can buy premium placement now or hold spend for later.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Buy Placement',
            preview: 'Higher awareness and stronger opening readiness.',
            cashDelta: -330_000,
            scriptQualityDelta: 0,
            hypeDelta: 6,
            marketingDelta: 250_000,
          },
          {
            id: idFactory('opt'),
            label: 'Pass',
            preview: 'Keep powder dry for a later marketing burst.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
    {
      id: 'brand-integration-deal',
      category: 'finance',
      scope: 'project',
      targetPhases: ['production', 'distribution'],
      title: 'Brand Integration Offer',
      decisionTitle: 'Brand Integration Deal',
      body: 'A consumer brand offers placement money with approval rights.',
      cooldownWeeks: 5,
      baseWeight: 1,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Brand Integration Deal',
        body: `${projectTitle ?? 'The project'} can lock an integration package this week.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Take The Deal',
            preview: 'Improves cash, but creative perception softens slightly.',
            cashDelta: 450_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: -1,
            setFlag: 'brand_partner',
          },
          {
            id: idFactory('opt'),
            label: 'Decline',
            preview: 'No new money, but preserves brand identity.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: 1,
          },
        ],
      }),
    },
    {
      id: 'bridge-financing',
      category: 'finance',
      scope: 'studio',
      title: 'Bridge Financing Offer',
      decisionTitle: 'Bridge Financing Term Sheet',
      body: 'A lender offers a short facility to smooth production cashflow.',
      cooldownWeeks: 7,
      baseWeight: 0.9,
      minWeek: 2,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Bridge Financing Term Sheet',
        body: 'The facility gives breathing room now but can hurt your heat if overused.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Draw Facility',
            preview: 'Immediate cash cushion at reputation cost.',
            cashDelta: 1_200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: -2,
            setFlag: 'bridge_debt',
          },
          {
            id: idFactory('opt'),
            label: 'Stay Lean',
            preview: 'No debt draw and stronger market discipline signal.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 1,
            clearFlag: 'bridge_debt',
          },
        ],
      }),
    },
    {
      id: 'agency-package-push',
      category: 'talent',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Agency Package Push',
      decisionTitle: 'Agency Packaging Proposal',
      body: 'A major agency offers a packaged talent bundle with a short deadline.',
      cooldownWeeks: 5,
      baseWeight: 0.95,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Agency Packaging Proposal',
        body: `${projectTitle ?? 'The project'} can move faster if you accept packaged attachments.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Package Terms',
            preview: 'Faster schedule and buzz, with a meaningful upfront cost.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            scheduleDelta: -1,
            studioHeatDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Run Open Market',
            preview: 'Keep flexibility and preserve cash.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
    {
      id: 'star-renegotiation-shock',
      category: 'talent',
      scope: 'project',
      targetPhases: ['production', 'postProduction'],
      blocksArc: { id: 'talent-meltdown', status: 'resolved' },
      title: 'Star Renegotiation Shock',
      decisionTitle: 'Star Renegotiation Ultimatum',
      body: 'Lead talent requests major contract revisions after early buzz tracking.',
      cooldownWeeks: 7,
      baseWeight: 0.95,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        arcId: 'talent-meltdown',
        arcStage: 0,
        title: 'Star Renegotiation Ultimatum',
        body: `${projectTitle ?? 'The production'} has 48 hours to answer talent demands.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Pay Upfront Premium',
            preview: 'Stabilize set now but set a costly precedent.',
            cashDelta: -340_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            setArcStage: 1,
            setFlag: 'star_fragile',
          },
          {
            id: idFactory('opt'),
            label: 'Hold Firm On Terms',
            preview: 'Save money now with elevated blowback risk.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            studioHeatDelta: -1,
            setArcStage: 1,
            setFlag: 'star_fragile',
          },
        ],
      }),
    },
    {
      id: 'tabloid-on-set-leak',
      category: 'talent',
      scope: 'project',
      targetPhases: ['production', 'postProduction', 'distribution'],
      requiresArc: { id: 'talent-meltdown', minStage: 1, status: 'active' },
      title: 'Tabloid Set Leak',
      decisionTitle: 'Star PR Crisis',
      body: 'A tabloid leak alleges toxic on-set behavior around your lead talent.',
      cooldownWeeks: 8,
      baseWeight: 1.05,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        arcId: 'talent-meltdown',
        arcStage: 1,
        title: 'Star PR Crisis',
        body: `${projectTitle ?? 'The title'} now faces a narrative war before release.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Back Talent Publicly',
            preview: 'Defend the star, protect hype, risk credibility hit if it worsens.',
            cashDelta: -110_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: -1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Neutral Compliance Statement',
            preview: 'Lower volatility path with moderate trust rebuild.',
            cashDelta: -80_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: 1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Quiet Settlement Package',
            preview: 'Expensive containment; likely closes the incident cycle.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            studioHeatDelta: 2,
            clearFlag: 'star_fragile',
            resolveArc: true,
          },
        ],
      }),
    },
    {
      id: 'talent-endgame-judgment',
      category: 'talent',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresArc: { id: 'talent-meltdown', minStage: 2, status: 'active' },
      title: 'Talent Endgame Judgment',
      decisionTitle: 'Final Talent Fallout Decision',
      body: 'Distributors demand confidence in campaign leadership before final push.',
      cooldownWeeks: 9,
      baseWeight: 0.9,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        arcId: 'talent-meltdown',
        arcStage: 2,
        title: 'Final Talent Fallout Decision',
        body: `${projectTitle ?? 'The campaign'} must choose between loyalty, replacement optics, or retreat.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Stand By Star',
            preview: 'High-risk loyalty play with major upside if audience follows.',
            cashDelta: -140_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            studioHeatDelta: -1,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Reframe Campaign Around Craft',
            preview: 'Costly pivot that de-emphasizes personality narrative.',
            cashDelta: -220_000,
            scriptQualityDelta: 0.2,
            hypeDelta: 1,
            studioHeatDelta: 2,
            clearFlag: 'star_fragile',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Slash Exposure And Coast',
            preview: 'Protect remaining budget at clear momentum cost.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -3,
            studioHeatDelta: -3,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'exclusivity-term-sheet',
      category: 'finance',
      scope: 'project',
      targetPhases: ['distribution'],
      blocksArc: { id: 'exhibitor-war', status: 'resolved' },
      title: 'Exhibitor Exclusivity Demand',
      decisionTitle: 'Exclusivity Term Sheet',
      body: 'Top exhibitors offer premium screens in exchange for stricter exclusivity terms.',
      cooldownWeeks: 7,
      baseWeight: 1.05,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'exhibitor-war',
        arcStage: 0,
        title: 'Exclusivity Term Sheet',
        body: `${projectTitle ?? 'The release'} can gain footprint now, but at strategic cost.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Hard Exclusivity',
            preview: 'Better placement now; narrower flexibility later.',
            cashDelta: 280_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            setArcStage: 1,
            setFlag: 'exhibitor_locked',
          },
          {
            id: idFactory('opt'),
            label: 'Negotiate Hybrid Terms',
            preview: 'Smaller upside now with some strategic flexibility preserved.',
            cashDelta: 120_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Decline And Stay Flexible',
            preview: 'No immediate cash, but avoids dependency.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'rival-screen-squeeze',
      category: 'operations',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresArc: { id: 'exhibitor-war', minStage: 1, status: 'active' },
      title: 'Rival Screen Squeeze',
      decisionTitle: 'Screen Share Countermove',
      body: 'A rival studio books aggressive previews and threatens your prime slots.',
      cooldownWeeks: 8,
      baseWeight: 1.1,
      minWeek: 7,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        arcId: 'exhibitor-war',
        arcStage: 1,
        title: 'Screen Share Countermove',
        body: `${projectTitle ?? 'The release'} must react before allocations lock.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Pay Local Exhibitor Support',
            preview: 'Defend footprint with targeted spend.',
            cashDelta: -240_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Shift To Alternate Markets',
            preview: 'Reduce conflict but soften domestic launch optics.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            studioHeatDelta: 0,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Hold And Absorb',
            preview: 'No spend now; risk deeper slot erosion.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            studioHeatDelta: -1,
            setArcStage: 2,
          },
        ],
      }),
    },
    {
      id: 'opening-weekend-lockout',
      category: 'finance',
      scope: 'project',
      targetPhases: ['released'],
      requiresArc: { id: 'exhibitor-war', minStage: 2, status: 'active' },
      title: 'Opening Weekend Lockout Threat',
      decisionTitle: 'Exhibitor Lockout Crisis',
      body: 'Two chains threaten reduced showtimes unless terms are amended before weekend.',
      cooldownWeeks: 10,
      baseWeight: 0.95,
      minWeek: 9,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'exhibitor-war',
        arcStage: 2,
        title: 'Exhibitor Lockout Crisis',
        body: `${projectTitle ?? 'The title'} is one negotiation away from a major footprint swing.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Concede Revenue Points',
            preview: 'Pay through split to secure broad weekend access.',
            cashDelta: -300_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 1,
            clearFlag: 'exhibitor_locked',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Pivot To Premium + Events',
            preview: 'Smaller footprint, higher intensity rollout.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Refuse Terms',
            preview: 'Protect principles and cash, accept opening damage.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -4,
            studioHeatDelta: -3,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'franchise-rights-window',
      category: 'finance',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      blocksArc: { id: 'franchise-pivot', status: 'resolved' },
      title: 'Franchise Rights Window',
      decisionTitle: 'Franchise Rights Reversion',
      body: 'Underlying rights for follow-up stories can be locked now before outside bidders move.',
      cooldownWeeks: 9,
      baseWeight: 0.85,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'franchise-pivot',
        arcStage: 0,
        title: 'Franchise Rights Reversion',
        body: `${projectTitle ?? 'The property'} can become a long-tail asset if you commit early.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Secure Sequel Rights',
            preview: 'Upfront spend for future optionality and leverage.',
            cashDelta: -420_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 1,
            setFlag: 'franchise_rights',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Pass On Rights',
            preview: 'Stay focused on current slate and preserve capital.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'universe-room-pitch',
      category: 'creative',
      scope: 'studio',
      requiresArc: { id: 'franchise-pivot', minStage: 1, status: 'active' },
      title: 'Universe Room Proposal',
      decisionTitle: 'Franchise Room Summit',
      body: 'Development proposes a connected slate room for sequel and spin-off planning.',
      cooldownWeeks: 10,
      baseWeight: 0.9,
      minWeek: 10,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'creative',
        arcId: 'franchise-pivot',
        arcStage: 1,
        title: 'Franchise Room Summit',
        body: 'Commit to a universe strategy now or keep a standalone identity.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund Franchise Room',
            preview: 'Strategic depth and long-tail upside at real annual cost.',
            cashDelta: -360_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            setArcStage: 2,
            setFlag: 'franchise_room',
          },
          {
            id: idFactory('opt'),
            label: 'Keep Standalone Focus',
            preview: 'Protect flexibility and avoid sequel pressure.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: 1,
            clearFlag: 'franchise_room',
            resolveArc: true,
          },
        ],
      }),
    },
    {
      id: 'flagship-greenlight-crossroads',
      category: 'creative',
      scope: 'studio',
      requiresArc: { id: 'franchise-pivot', minStage: 2, status: 'active' },
      title: 'Flagship Greenlight Crossroads',
      decisionTitle: 'Franchise Flagship Decision',
      body: 'Board asks for final call: flagship sequel slate or return to originals-only mandate.',
      cooldownWeeks: 12,
      baseWeight: 0.8,
      minWeek: 12,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'creative',
        arcId: 'franchise-pivot',
        arcStage: 2,
        title: 'Franchise Flagship Decision',
        body: 'This choice defines studio identity for the next cycle.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Commit To Flagship Franchise',
            preview: 'Higher commercial ceiling with stronger volatility profile.',
            cashDelta: -520_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            studioHeatDelta: 3,
            setFlag: 'franchise_committed',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Return To Originals',
            preview: 'Lower upside but cleaner creative identity and balance.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            clearFlag: 'franchise_room',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Delay Strategic Decision',
            preview: 'Short-term flexibility at long-term credibility cost.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            studioHeatDelta: -2,
            failArc: true,
          },
        ],
      }),
    },
  ];
}
