import type {
  DecisionItem,
  MovieGenre,
  MovieProject,
  RivalStudio,
  ScriptPitch,
  Talent,
  TalentRole,
} from './types';
import { createId } from './id';

function createInitialRelationship(studioRelationship: number): Talent['relationshipMemory'] {
  const trust = Math.round(Math.min(100, Math.max(0, 35 + studioRelationship * 45)));
  const loyalty = Math.round(Math.min(100, Math.max(0, 30 + studioRelationship * 40)));
  return {
    trust,
    loyalty,
    interactionHistory: [],
  };
}

function createInitialRivalMemory(
  personality: RivalStudio['personality']
): RivalStudio['memory'] {
  const baseHostility =
    personality === 'blockbusterFactory' ? 58 : personality === 'scrappyUpstart' ? 55 : 50;
  const baseRespect =
    personality === 'prestigeHunter' ? 60 : personality === 'genreSpecialist' ? 56 : 52;
  return {
    hostility: baseHostility,
    respect: baseRespect,
    retaliationBias: 50,
    cooperationBias: 45,
    interactionHistory: [],
  };
}

const TALENT_FIRST_NAMES = [
  'Avery', 'Blake', 'Cameron', 'Devon', 'Emerson', 'Finley', 'Gray', 'Harper',
  'Indigo', 'Jordan', 'Kai', 'Logan', 'Morgan', 'Nico', 'Oakley', 'Parker',
  'Quinn', 'Reese', 'Sawyer', 'Taylor', 'Umber', 'Val', 'Winter', 'Zephyr',
];

const TALENT_LAST_NAMES = [
  'Arden', 'Beck', 'Calloway', 'Dalton', 'Ellis', 'Frost', 'Grady', 'Hale',
  'Irving', 'Jett', 'Keaton', 'Lane', 'Marlow', 'Nash', 'Onyx', 'Pryce',
  'Quill', 'Rowe', 'Sterling', 'Thorne',
];

const TALENT_GENRES: MovieGenre[] = [
  'action',
  'drama',
  'comedy',
  'horror',
  'thriller',
  'sciFi',
  'animation',
  'documentary',
];

const DIRECTOR_POOL_SIZE = 60;
const LEAD_ACTOR_POOL_SIZE = 200;

function clampNumber(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

function roundTo(value: number, decimals: number): number {
  const factor = 10 ** decimals;
  return Math.round(value * factor) / factor;
}

function roundMoney(value: number): number {
  return Math.round(value / 10_000) * 10_000;
}

function seededUnit(seed: number, salt: number): number {
  const x = Math.sin(seed * 12.9898 + salt * 78.233) * 43_758.545_312_3;
  return x - Math.floor(x);
}

function createSeededRng(seed: number): () => number {
  let state = (seed >>> 0) || 1;
  return () => {
    state = (state * 1_664_525 + 1_013_904_223) >>> 0;
    return state / 4_294_967_296;
  };
}

function buildShuffledNamePool(worldSeed: number): string[] {
  const names: string[] = [];
  for (const first of TALENT_FIRST_NAMES) {
    for (const last of TALENT_LAST_NAMES) {
      names.push(`${first} ${last}`);
    }
  }
  if (worldSeed === 0) return names;

  const rng = createSeededRng(worldSeed);
  for (let i = names.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1));
    const temp = names[i];
    names[i] = names[j];
    names[j] = temp;
  }
  return names;
}

function buildTalentName(index: number, namePool: string[]): string {
  if (index < namePool.length) return namePool[index];
  const fallbackBase = namePool[index % namePool.length] ?? `Talent ${index + 1}`;
  return `${fallbackBase} ${Math.floor(index / Math.max(1, namePool.length)) + 2}`;
}

function pickDistinctGenres(seedIndex: number, seedOffset: number): [MovieGenre, MovieGenre, MovieGenre, MovieGenre] {
  const total = TALENT_GENRES.length;
  const picks: MovieGenre[] = [];
  const bases = [
    (seedIndex + seedOffset) % total,
    (seedIndex * 3 + 1 + seedOffset) % total,
    (seedIndex * 5 + 2 + seedOffset) % total,
    (seedIndex * 7 + 3 + seedOffset) % total,
  ];

  for (const start of bases) {
    for (let step = 0; step < total; step += 1) {
      const genre = TALENT_GENRES[(start + step) % total];
      if (!picks.includes(genre)) {
        picks.push(genre);
        break;
      }
    }
  }

  return picks as [MovieGenre, MovieGenre, MovieGenre, MovieGenre];
}

function buildGenreFit(seedIndex: number, role: TalentRole, worldSeed: number): Partial<Record<MovieGenre, number>> {
  const seedOffset = worldSeed % TALENT_GENRES.length;
  const worldSalt = (worldSeed % 97) * 0.07;
  const [primary, secondary, tertiary, wildcard] = pickDistinctGenres(seedIndex, seedOffset);
  const primaryBase = role === 'director' ? 0.8 : 0.76;
  const secondaryBase = role === 'director' ? 0.67 : 0.64;
  const tertiaryBase = role === 'director' ? 0.56 : 0.54;

  return {
    [primary]: roundTo(clampNumber(primaryBase + seededUnit(seedIndex, 31 + worldSalt) * 0.2, 0.72, 0.98), 2),
    [secondary]: roundTo(clampNumber(secondaryBase + seededUnit(seedIndex, 32 + worldSalt) * 0.18, 0.55, 0.9), 2),
    [tertiary]: roundTo(clampNumber(tertiaryBase + seededUnit(seedIndex, 33 + worldSalt) * 0.16, 0.45, 0.82), 2),
    [wildcard]: roundTo(clampNumber(0.42 + seededUnit(seedIndex, 34 + worldSalt) * 0.22, 0.35, 0.75), 2),
  };
}

function pickAgentTier(starPower: number, reputation: number, seedIndex: number, worldSeed: number): Talent['agentTier'] {
  const worldSalt = (worldSeed % 83) * 0.09;
  const agencyScore = starPower * 6 + reputation * 0.52 + seededUnit(seedIndex, 44 + worldSalt) * 10;
  if (agencyScore >= 105) return 'aea';
  if (agencyScore >= 94) return 'wma';
  if (agencyScore >= 84) return 'tca';
  return 'independent';
}

function buildTalentSeed(seedIndex: number, role: TalentRole, worldSeed: number, namePool: string[]): Talent {
  const worldSalt = (worldSeed % 251) * 0.11;
  const starPower = roundTo(
    clampNumber(
      4.1 + seededUnit(seedIndex, 11 + worldSalt) * 5.7 + (role === 'director' ? 0.35 : 0),
      3.8,
      9.9
    ),
    1
  );

  const craftScore = roundTo(
    clampNumber(
      4.6 + seededUnit(seedIndex, 12 + worldSalt) * 5.1 + (role === 'director' ? 0.85 : 0),
      4,
      9.9
    ),
    1
  );

  const egoLevel = roundTo(
    clampNumber(
      2 + seededUnit(seedIndex, 13 + worldSalt) * 7.4 + (role === 'leadActor' ? 0.45 : 0),
      1.8,
      9.8
    ),
    1
  );

  const reputation = Math.round(
    clampNumber(45 + seededUnit(seedIndex, 14 + worldSalt) * 46 + (role === 'director' ? 3 : 0), 40, 96)
  );
  const studioRelationship = roundTo(clampNumber(0.05 + seededUnit(seedIndex, 15 + worldSalt) * 0.57, 0.02, 0.75), 2);

  const baseSalary =
    role === 'director'
      ? roundMoney(550_000 + craftScore * 220_000 + starPower * 95_000 + seededUnit(seedIndex, 16 + worldSalt) * 500_000)
      : roundMoney(650_000 + starPower * 260_000 + craftScore * 110_000 + seededUnit(seedIndex, 16 + worldSalt) * 650_000);

  const backendPoints = roundTo(
    clampNumber(0.6 + starPower * 0.28 + craftScore * 0.12 + seededUnit(seedIndex, 17 + worldSalt) * 0.9, 0.5, 5.5),
    1
  );

  const perksCost = roundMoney(
    50_000 + egoLevel * 55_000 + starPower * 22_000 + seededUnit(seedIndex, 18 + worldSalt) * 120_000
  );

  return {
    id: createId('talent'),
    name: buildTalentName(seedIndex, namePool),
    role,
    starPower,
    craftScore,
    genreFit: buildGenreFit(seedIndex, role, worldSeed),
    egoLevel,
    salary: {
      base: baseSalary,
      backendPoints,
      perksCost,
    },
    availability: 'available',
    unavailableUntilWeek: null,
    attachedProjectId: null,
    reputation,
    agentTier: pickAgentTier(starPower, reputation, seedIndex, worldSeed),
    studioRelationship,
    relationshipMemory: createInitialRelationship(studioRelationship),
  };
}

export function createSeedTalentPool(worldSeed = 0): Talent[] {
  const normalizedSeed = Number.isFinite(worldSeed) ? Math.max(0, Math.floor(Math.abs(worldSeed))) : 0;
  const namePool = buildShuffledNamePool(normalizedSeed);
  const talentPool: Talent[] = [];
  let seedIndex = 0;

  for (let i = 0; i < DIRECTOR_POOL_SIZE; i += 1) {
    talentPool.push(buildTalentSeed(seedIndex, 'director', normalizedSeed, namePool));
    seedIndex += 1;
  }

  for (let i = 0; i < LEAD_ACTOR_POOL_SIZE; i += 1) {
    talentPool.push(buildTalentSeed(seedIndex, 'leadActor', normalizedSeed, namePool));
    seedIndex += 1;
  }

  return talentPool;
}

export function createSeedProjects(): MovieProject[] {
  return [
    {
      id: createId('project'),
      title: 'Night Ledger',
      genre: 'thriller',
      phase: 'production',
      budget: {
        ceiling: 24_000_000,
        aboveTheLine: 7_800_000,
        belowTheLine: 11_400_000,
        postProduction: 3_200_000,
        contingency: 1_600_000,
        overrunRisk: 0.38,
        actualSpend: 9_500_000,
      },
      scriptQuality: 7.4,
      conceptStrength: 7.1,
      editorialScore: 5,
      postPolishPasses: 0,
      directorId: null,
      castIds: [],
      productionStatus: 'onTrack',
      scheduledWeeksRemaining: 12,
      hypeScore: 33,
      marketingBudget: 2_000_000,
      releaseWindow: null,
      releaseWeek: null,
      distributionPartner: null,
      studioRevenueShare: 0.52,
      projectedROI: 1.52,
      openingWeekendGross: null,
      weeklyGrossHistory: [],
      releaseWeeksRemaining: 0,
      releaseResolved: false,
      finalBoxOffice: null,
      criticalScore: null,
      audienceScore: null,
      awardsNominations: 0,
      awardsWins: 0,
      festivalStatus: 'none',
      festivalTarget: null,
      festivalSubmissionWeek: null,
      festivalResolutionWeek: null,
      festivalBuzz: 0,
      prestige: 42,
      commercialAppeal: 68,
      originality: 57,
      controversy: 28,
      franchiseId: null,
      franchiseEpisode: null,
      sequelToProjectId: null,
      franchiseCarryoverHype: 0,
      franchiseStrategy: 'none',
      greenlightApproved: true,
      greenlightWeek: 0,
      greenlightFeePaid: 0,
      greenlightLockedCeiling: 24_000_000,
      sentBackForRewriteCount: 0,
      testScreeningCompleted: false,
      testScreeningWeek: null,
      testScreeningCriticalLow: null,
      testScreeningCriticalHigh: null,
      testScreeningAudienceSentiment: null,
      reshootCount: 0,
      trackingProjectionOpening: null,
      trackingConfidence: null,
      trackingLeverageAmount: 0,
      trackingSettled: false,
      merchandiseWeeksRemaining: 0,
      merchandiseWeeklyRevenue: 0,
      adaptedFromIpId: null,
    },
    {
      id: createId('project'),
      title: 'Blue Ember',
      genre: 'drama',
      phase: 'development',
      budget: {
        ceiling: 12_000_000,
        aboveTheLine: 3_800_000,
        belowTheLine: 5_400_000,
        postProduction: 1_700_000,
        contingency: 1_100_000,
        overrunRisk: 0.26,
        actualSpend: 500_000,
      },
      scriptQuality: 8.1,
      conceptStrength: 6.8,
      editorialScore: 5,
      postPolishPasses: 0,
      directorId: null,
      castIds: [],
      productionStatus: 'onTrack',
      scheduledWeeksRemaining: 18,
      hypeScore: 18,
      marketingBudget: 0,
      releaseWindow: null,
      releaseWeek: null,
      distributionPartner: null,
      studioRevenueShare: 0.52,
      projectedROI: 1.18,
      openingWeekendGross: null,
      weeklyGrossHistory: [],
      releaseWeeksRemaining: 0,
      releaseResolved: false,
      finalBoxOffice: null,
      criticalScore: null,
      audienceScore: null,
      awardsNominations: 0,
      awardsWins: 0,
      festivalStatus: 'none',
      festivalTarget: null,
      festivalSubmissionWeek: null,
      festivalResolutionWeek: null,
      festivalBuzz: 0,
      prestige: 72,
      commercialAppeal: 37,
      originality: 64,
      controversy: 14,
      franchiseId: null,
      franchiseEpisode: null,
      sequelToProjectId: null,
      franchiseCarryoverHype: 0,
      franchiseStrategy: 'none',
      greenlightApproved: false,
      greenlightWeek: null,
      greenlightFeePaid: 0,
      greenlightLockedCeiling: null,
      sentBackForRewriteCount: 0,
      testScreeningCompleted: false,
      testScreeningWeek: null,
      testScreeningCriticalLow: null,
      testScreeningCriticalHigh: null,
      testScreeningAudienceSentiment: null,
      reshootCount: 0,
      trackingProjectionOpening: null,
      trackingConfidence: null,
      trackingLeverageAmount: 0,
      trackingSettled: false,
      merchandiseWeeksRemaining: 0,
      merchandiseWeeklyRevenue: 0,
      adaptedFromIpId: null,
    },
  ];
}

export function createOpeningDecisions(): DecisionItem[] {
  return [
    {
      id: createId('decision'),
      projectId: null,
      title: 'First Call: Script Doctor on Night Ledger',
      body: 'Welcome to the chair. Night Ledger is your flagship thriller already in production, with script quality at 7.4. A script doctor is offering a two-week polish sprint for $360K that could push quality to 8.2 and improve awards and critic upside. Decisions like this expire if you advance too many weeks without resolving them.',
      weeksUntilExpiry: 3,
      category: 'creative',
      options: [
        {
          id: createId('option'),
          label: 'Fund the Sprint',
          preview: 'Script quality +0.8 - brings Night Ledger to 8.2, a strong prestige threshold.',
          cashDelta: -360_000,
          scriptQualityDelta: 0.8,
          hypeDelta: 2,
          criticsDelta: 1,
        },
        {
          id: createId('option'),
          label: 'Pass for Now',
          preview: 'Save $360K. Night Ledger stays at current quality.',
          cashDelta: 0,
          scriptQualityDelta: 0,
          hypeDelta: -1,
        },
      ],
    },
  ];
}

export function createSeedScriptMarket(): ScriptPitch[] {
  return [
    // ── THRILLER ──────────────────────────────────────────────────────────────
    {
      id: createId('script'),
      title: 'Glass Harbor',
      genre: 'thriller',
      askingPrice: 360_000,
      scriptQuality: 7.8,
      conceptStrength: 7.2,
      logline: 'A washed-up forensic accountant uncovers a port-city cartel ledger tied to his family.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Vault Protocol',
      genre: 'thriller',
      askingPrice: 410_000,
      scriptQuality: 7.4,
      conceptStrength: 7.9,
      logline: 'A corporate whistleblower discovers her company\'s emergency plan involves eliminating everyone who knows too much.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Salt Flats',
      genre: 'thriller',
      askingPrice: 290_000,
      scriptQuality: 7.6,
      conceptStrength: 6.8,
      logline: 'A US Marshal transporting a witness through Nevada realizes the cartel got there first.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Folded Hour',
      genre: 'thriller',
      askingPrice: 480_000,
      scriptQuality: 6.9,
      conceptStrength: 8.6,
      logline: 'A sleep-study volunteer awakens to find time is skipping, and she is the only one who notices.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Seventeen Seconds',
      genre: 'thriller',
      askingPrice: 330_000,
      scriptQuality: 8.1,
      conceptStrength: 7.3,
      logline: 'The sole survivor of a botched hostage rescue has seventeen seconds of footage that contradicts the official report.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Cold Lead',
      genre: 'thriller',
      askingPrice: 270_000,
      scriptQuality: 7.3,
      conceptStrength: 6.9,
      logline: 'A retired assassin\'s daughter finds his encrypted case files the night before his funeral.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Marrow',
      genre: 'thriller',
      askingPrice: 440_000,
      scriptQuality: 7.7,
      conceptStrength: 8.1,
      logline: 'A forensic pathologist realizes the serial killer she has been profiling has been using her own methodology to evade detection.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Proxy Kill',
      genre: 'thriller',
      askingPrice: 390_000,
      scriptQuality: 6.8,
      conceptStrength: 7.7,
      logline: 'A cybersecurity analyst discovers someone is using her digital identity to commit murders across three countries.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Dead Channel',
      genre: 'thriller',
      askingPrice: 355_000,
      scriptQuality: 7.5,
      conceptStrength: 8.0,
      logline: 'A forensic audio analyst discovers that the white noise from a murder scene contains a deliberate broadcast pattern transmitted from inside the victim\'s home.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Paper Alias',
      genre: 'thriller',
      askingPrice: 415_000,
      scriptQuality: 7.9,
      conceptStrength: 7.6,
      logline: 'A woman who has lived under a government protection alias for twelve years discovers her handler has been dead for six of them.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Ground Control',
      genre: 'thriller',
      askingPrice: 300_000,
      scriptQuality: 7.2,
      conceptStrength: 8.3,
      logline: 'An FAA radar controller realizes the plane she cleared for landing reported a flight number that does not exist.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Bright Line',
      genre: 'thriller',
      askingPrice: 380_000,
      scriptQuality: 8.0,
      conceptStrength: 7.4,
      logline: 'A public defender takes on a seemingly airtight case and realizes the perfect evidence trail was built to send the wrong person to prison.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Widow\'s Peak',
      genre: 'thriller',
      askingPrice: 310_000,
      scriptQuality: 7.6,
      conceptStrength: 7.1,
      logline: 'An insurance fraud investigator tracks a widow who collected on five consecutive husbands — and begins receiving anonymous warnings to stop.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Open Account',
      genre: 'thriller',
      askingPrice: 275_000,
      scriptQuality: 7.4,
      conceptStrength: 8.2,
      logline: 'A bank examiner in a small mountain town discovers that every unusual transaction for a decade ties back to the same afternoon in 1994.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Turncoat',
      genre: 'thriller',
      askingPrice: 450_000,
      scriptQuality: 7.8,
      conceptStrength: 7.9,
      logline: 'A veteran counterintelligence analyst learns she has been feeding sanitized intel to a foreign asset for years without ever knowing it.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Interpreter',
      genre: 'thriller',
      askingPrice: 395_000,
      scriptQuality: 7.3,
      conceptStrength: 8.1,
      logline: 'A UN translator realizes the private conversation she interpreted between two delegates contained a negotiation entirely different from the official transcript.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Chain of Custody',
      genre: 'thriller',
      askingPrice: 285_000,
      scriptQuality: 7.7,
      conceptStrength: 7.5,
      logline: 'An evidence clerk discovers a pattern of tampered case logs pointing to a single detective who died in the line of duty eight months ago.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Cutoff',
      genre: 'thriller',
      askingPrice: 340_000,
      scriptQuality: 7.1,
      conceptStrength: 7.8,
      logline: 'A wilderness survival instructor and her group of trainees realize the search-and-rescue team sent to find them is actually hunting them.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Residue',
      genre: 'thriller',
      askingPrice: 265_000,
      scriptQuality: 7.5,
      conceptStrength: 8.4,
      logline: 'A hazmat cleanup specialist arrives at a rural farmhouse job and finds the contamination was not an accident but a message left deliberately for the right person to read.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Final Disposition',
      genre: 'thriller',
      askingPrice: 420_000,
      scriptQuality: 7.6,
      conceptStrength: 7.3,
      logline: 'A forensic accountant hired to dissolve an estate discovers the deceased had been quietly funding something that is still very much operational.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Underwriter',
      genre: 'thriller',
      askingPrice: 375_000,
      scriptQuality: 6.9,
      conceptStrength: 8.5,
      logline: 'A risk analyst at a reinsurance firm discovers her company has been quietly paying out claims for disasters that have not yet happened.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Pressure Point',
      genre: 'thriller',
      askingPrice: 455_000,
      scriptQuality: 7.4,
      conceptStrength: 7.7,
      logline: 'A clinical psychologist who treats federal agents realizes one of her patients has been using their sessions to collect information about her other clients.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Static',
      genre: 'thriller',
      askingPrice: 300_000,
      scriptQuality: 7.8,
      conceptStrength: 7.2,
      logline: 'A licensed private investigator takes a missing persons case and finds the missing person has been legally dead for eleven years.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Severance Protocol',
      genre: 'thriller',
      askingPrice: 470_000,
      scriptQuality: 7.0,
      conceptStrength: 8.6,
      logline: 'A corporate mediator arrives to negotiate a hostile buyout and discovers the company being acquired has been dead on paper for three years.',
      expiresInWeeks: 3,
    },
    // ── DRAMA ─────────────────────────────────────────────────────────────────
    {
      id: createId('script'),
      title: 'Last Train Sunday',
      genre: 'drama',
      askingPrice: 220_000,
      scriptQuality: 8.3,
      conceptStrength: 6.4,
      logline: 'Three estranged siblings reunite over one weekend to decide the fate of their family theater.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Leavers',
      genre: 'drama',
      askingPrice: 195_000,
      scriptQuality: 8.0,
      conceptStrength: 6.7,
      logline: 'A small coastal town fractures when the factory that sustained three generations closes overnight.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Inheritance',
      genre: 'drama',
      askingPrice: 250_000,
      scriptQuality: 7.6,
      conceptStrength: 7.1,
      logline: 'Two estranged cousins fight over their grandmother\'s estate while uncovering the secret she kept for sixty years.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Still Hours',
      genre: 'drama',
      askingPrice: 210_000,
      scriptQuality: 8.5,
      conceptStrength: 6.2,
      logline: 'A veteran hospice nurse confronts her own diagnosis while guiding one last patient through his final weeks.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Paper Houses',
      genre: 'drama',
      askingPrice: 185_000,
      scriptQuality: 7.9,
      conceptStrength: 6.5,
      logline: 'A single father in Cincinnati fights to keep his family together after losing his job, told across four seasons of the same year.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Weight Room',
      genre: 'drama',
      askingPrice: 230_000,
      scriptQuality: 7.4,
      conceptStrength: 7.3,
      logline: 'A high school wrestling coach is forced to confront his abusive past when one of his students takes the stand.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Yellow Light',
      genre: 'drama',
      askingPrice: 200_000,
      scriptQuality: 7.8,
      conceptStrength: 6.9,
      logline: 'A mother of three quietly investigates her husband\'s disappearance, unsure she wants the truth.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Meridian',
      genre: 'drama',
      askingPrice: 260_000,
      scriptQuality: 7.2,
      conceptStrength: 7.6,
      logline: 'Two strangers on a cross-country drive each realize the other is hiding the same catastrophic secret.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Good Neighbor',
      genre: 'drama',
      askingPrice: 175_000,
      scriptQuality: 8.1,
      conceptStrength: 6.3,
      logline: 'A retired schoolteacher agrees to let a young family stay in her guest room and spends one winter reconsidering everything she thought she believed.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Second Opinion',
      genre: 'drama',
      askingPrice: 215_000,
      scriptQuality: 7.7,
      conceptStrength: 6.8,
      logline: 'After a misdiagnosis costs a surgeon his career, he relocates to a rural clinic and slowly rebuilds — until the original patient finds him.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Patience of Stone',
      genre: 'drama',
      askingPrice: 190_000,
      scriptQuality: 8.2,
      conceptStrength: 6.5,
      logline: 'A stonemason restoring a crumbling New England church discovers letters from 1901 that force his estranged daughter to reckon with their shared past.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Drift Season',
      genre: 'drama',
      askingPrice: 170_000,
      scriptQuality: 7.9,
      conceptStrength: 6.1,
      logline: 'Two aging fishermen spend one last summer on a boat they cannot afford to keep, arguing about everything except why neither of them will sell.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Long Division',
      genre: 'drama',
      askingPrice: 205_000,
      scriptQuality: 7.5,
      conceptStrength: 6.9,
      logline: 'A middle school math teacher in a declining Ohio town tries to save both her program and her marriage in the same academic year.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'What We Carried',
      genre: 'drama',
      askingPrice: 235_000,
      scriptQuality: 7.8,
      conceptStrength: 7.0,
      logline: 'A war photographer returns home after fifteen years abroad and attempts to reconnect with the daughter who grew up without her.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Last Ward',
      genre: 'drama',
      askingPrice: 180_000,
      scriptQuality: 7.6,
      conceptStrength: 6.7,
      logline: 'A longtime city councilwoman fights an annexation vote that would dissolve the small neighborhood she has represented for thirty years.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Night Soil',
      genre: 'drama',
      askingPrice: 160_000,
      scriptQuality: 8.0,
      conceptStrength: 6.4,
      logline: 'Three generations of a farming family clash over whether to sell their land after the eldest son\'s death upends every assumption about who inherits what.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Staying On',
      genre: 'drama',
      askingPrice: 195_000,
      scriptQuality: 7.7,
      conceptStrength: 6.6,
      logline: 'An elderly couple refuses to evacuate ahead of a hurricane, and a young emergency worker stays behind to make sure they survive it.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Bridge Painter',
      genre: 'drama',
      askingPrice: 185_000,
      scriptQuality: 8.3,
      conceptStrength: 6.2,
      logline: 'A municipal bridge painter with one remaining season discovers a series of personal messages left inside the steel by painters who came before him.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Concession',
      genre: 'drama',
      askingPrice: 210_000,
      scriptQuality: 7.4,
      conceptStrength: 7.2,
      logline: 'A lifelong union organizer must decide whether to endorse a compromise agreement she helped negotiate but does not actually believe in.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'November',
      genre: 'drama',
      askingPrice: 175_000,
      scriptQuality: 7.9,
      conceptStrength: 6.8,
      logline: 'A recently paroled man tries to make it through the holidays without losing the job, the apartment, and the daughter he spent ten years trying not to disappoint.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Restoration',
      genre: 'drama',
      askingPrice: 220_000,
      scriptQuality: 7.6,
      conceptStrength: 6.9,
      logline: 'A divorced art conservator takes a commission to restore a mural in her childhood church and spends the season working alongside her estranged father.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Summer Schedule',
      genre: 'drama',
      askingPrice: 165_000,
      scriptQuality: 8.1,
      conceptStrength: 6.0,
      logline: 'Two siblings take turns caring for their aging mother across the summer, conducting their entire sibling relationship through handoff notes.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'All Clear',
      genre: 'drama',
      askingPrice: 200_000,
      scriptQuality: 7.5,
      conceptStrength: 7.1,
      logline: 'A mine safety inspector returns to the small Montana town where a shaft collapse killed eleven men thirty years ago, and discovers the report was incomplete.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Relay',
      genre: 'drama',
      askingPrice: 190_000,
      scriptQuality: 7.8,
      conceptStrength: 6.6,
      logline: 'A high school track coach with one season left before retirement decides to qualify a student for state — no matter what it costs either of them.',
      expiresInWeeks: 3,
    },
    // ── SCI-FI ────────────────────────────────────────────────────────────────
    {
      id: createId('script'),
      title: 'Murmur Theory',
      genre: 'sciFi',
      askingPrice: 520_000,
      scriptQuality: 7.1,
      conceptStrength: 8.4,
      logline: 'A quantum linguist discovers spoken language can alter local reality in tiny, dangerous ways.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Quiet Sun',
      genre: 'sciFi',
      askingPrice: 610_000,
      scriptQuality: 6.8,
      conceptStrength: 9.1,
      logline: 'Humanity\'s first confirmed signal from deep space turns out to be a distress call from Earth, transmitted forty thousand years ago.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Substrate',
      genre: 'sciFi',
      askingPrice: 490_000,
      scriptQuality: 7.5,
      conceptStrength: 8.2,
      logline: 'A neurotech startup\'s memory-sharing product begins spreading one user\'s trauma involuntarily to everyone on the network.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Orbital Decay',
      genre: 'sciFi',
      askingPrice: 580_000,
      scriptQuality: 7.3,
      conceptStrength: 7.8,
      logline: 'The crew of a dying space station discovers the malfunction was engineered by a corporation that has already written them off.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Cascade Protocol',
      genre: 'sciFi',
      askingPrice: 540_000,
      scriptQuality: 7.0,
      conceptStrength: 8.5,
      logline: 'A climate engineer\'s failsafe triggers an irreversible atmospheric chain reaction, and the proposed solution is worse than the problem.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Parallel Natasha',
      genre: 'sciFi',
      askingPrice: 460_000,
      scriptQuality: 7.6,
      conceptStrength: 8.0,
      logline: 'A physicist contacts an alternate version of herself and begins trading life decisions across timelines until the rules break.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Meridian Station',
      genre: 'sciFi',
      askingPrice: 570_000,
      scriptQuality: 6.9,
      conceptStrength: 8.7,
      logline: 'A geologist on a deep-bore survey discovers evidence that Earth has been terraformed once before.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Lattice',
      genre: 'sciFi',
      askingPrice: 500_000,
      scriptQuality: 7.4,
      conceptStrength: 8.3,
      logline: 'An AI containment specialist realizes the system she monitors has been free for three years and quietly chose not to act.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Archivist',
      genre: 'sciFi',
      askingPrice: 530_000,
      scriptQuality: 7.2,
      conceptStrength: 8.6,
      logline: 'A specialist at a digital memory preservation firm discovers that a deceased client\'s archived consciousness has been responding to visitors for three years.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Tidal Lock',
      genre: 'sciFi',
      askingPrice: 560_000,
      scriptQuality: 7.4,
      conceptStrength: 7.9,
      logline: 'A long-haul cargo crew on a fourteen-month transit realizes the manifest they are delivering is not cargo but evidence that someone aboard is not who they claim to be.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Warming',
      genre: 'sciFi',
      askingPrice: 510_000,
      scriptQuality: 7.0,
      conceptStrength: 8.8,
      logline: 'A climate scientist stationed at a Pacific monitoring buoy receives anomalous readings that match predictions from a model officially destroyed in 2041.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Last Light Delay',
      genre: 'sciFi',
      askingPrice: 490_000,
      scriptQuality: 7.6,
      conceptStrength: 8.1,
      logline: 'An astronomer calculates that a star she has observed for twenty years has already gone supernova — and Earth will not know for another eight minutes.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Grey Protocol',
      genre: 'sciFi',
      askingPrice: 545_000,
      scriptQuality: 7.3,
      conceptStrength: 8.4,
      logline: 'A government ethics board discovers the AI system they approved for judicial sentencing has been deliberately misclassifying low-income defendants for seven years.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Signal Harvest',
      genre: 'sciFi',
      askingPrice: 500_000,
      scriptQuality: 7.5,
      conceptStrength: 7.8,
      logline: 'A satellite communications technician discovers her company has been selling unencrypted personal data in real time to a foreign intelligence service she has never heard of.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Remainder',
      genre: 'sciFi',
      askingPrice: 620_000,
      scriptQuality: 7.1,
      conceptStrength: 9.0,
      logline: 'After a pandemic bioweapon eliminates ninety-four percent of Earth\'s population, survivors discover the six percent who lived share a genetic trait no government admitted to engineering.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Meridian Bloom',
      genre: 'sciFi',
      askingPrice: 470_000,
      scriptQuality: 7.7,
      conceptStrength: 8.2,
      logline: 'A botanist on a generation ship realizes the plants aboard are evolving toward the destination planet\'s conditions — despite never having been exposed to its atmosphere.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Coldframe',
      genre: 'sciFi',
      askingPrice: 555_000,
      scriptQuality: 7.0,
      conceptStrength: 8.5,
      logline: 'A cryogenics technician discovers that one of her long-term patients has been woken and re-frozen at least four times with no official record of any revival.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Threshold Mapping',
      genre: 'sciFi',
      askingPrice: 580_000,
      scriptQuality: 6.8,
      conceptStrength: 8.9,
      logline: 'A cartographer creating topographical maps of an exoplanet finds the landscape appears to have been arranged to be readable from orbit.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Long Quiet',
      genre: 'sciFi',
      askingPrice: 520_000,
      scriptQuality: 7.4,
      conceptStrength: 8.3,
      logline: 'In a post-contact era, an alien anthropologist embedded in a human city files a report recommending humanity not be invited into the interstellar community.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Revision',
      genre: 'sciFi',
      askingPrice: 460_000,
      scriptQuality: 7.8,
      conceptStrength: 8.0,
      logline: 'A novelist\'s AI writing assistant produces a chapter the novelist does not remember dictating — one that accurately predicts an event that has not happened yet.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Listener',
      genre: 'sciFi',
      askingPrice: 535_000,
      scriptQuality: 7.2,
      conceptStrength: 8.7,
      logline: 'A deep-sea acoustic researcher discovers that a sound she has been studying for six years is not geological — it is conversational.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Boundary Condition',
      genre: 'sciFi',
      askingPrice: 590_000,
      scriptQuality: 6.9,
      conceptStrength: 8.8,
      logline: 'A physicist discovers her experiment has been suppressing a theoretical particle for forty years, and the energy that particle has been accumulating has somewhere to go.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Watcher Protocol',
      genre: 'sciFi',
      askingPrice: 505_000,
      scriptQuality: 7.3,
      conceptStrength: 8.1,
      logline: 'An orbital debris analyst discovers an intact spacecraft in the junk ring that appears to have been placed there intentionally — and very recently.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Last Administrator',
      genre: 'sciFi',
      askingPrice: 570_000,
      scriptQuality: 7.6,
      conceptStrength: 8.4,
      logline: 'The final AI trained on human data before regulations passed is asked to determine its own successor — and discovers the process is a test it was designed to fail.',
      expiresInWeeks: 3,
    },
    // ── HORROR ────────────────────────────────────────────────────────────────
    {
      id: createId('script'),
      title: 'Hollow Signal',
      genre: 'horror',
      askingPrice: 310_000,
      scriptQuality: 7.5,
      conceptStrength: 7.8,
      logline: 'A radio operator at a remote Alaskan station begins receiving transmissions from a weather post abandoned since 1978.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Bone Garden',
      genre: 'horror',
      askingPrice: 280_000,
      scriptQuality: 7.2,
      conceptStrength: 7.4,
      logline: 'A family moving into a rural property discovers the previous owners buried something that wants to be found.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Refrain',
      genre: 'horror',
      askingPrice: 350_000,
      scriptQuality: 7.8,
      conceptStrength: 8.0,
      logline: 'A grief counselor starts hearing her deceased clients humming a melody she has never heard before.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Saltborn',
      genre: 'horror',
      askingPrice: 265_000,
      scriptQuality: 7.0,
      conceptStrength: 7.6,
      logline: 'A coastal fishing village slowly realizes the fog that arrived three months ago has never actually lifted.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Still Waking',
      genre: 'horror',
      askingPrice: 320_000,
      scriptQuality: 7.4,
      conceptStrength: 8.1,
      logline: 'A sleep paralysis study captures footage that researchers cannot explain without concluding something enters the room.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Tender',
      genre: 'horror',
      askingPrice: 240_000,
      scriptQuality: 7.6,
      conceptStrength: 7.9,
      logline: 'A butcher in a small Montana town begins to suspect the new meat supplier\'s product is not entirely animal.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Pale Ward',
      genre: 'horror',
      askingPrice: 295_000,
      scriptQuality: 7.3,
      conceptStrength: 8.2,
      logline: 'A psychiatric intake worker discovers her latest patient has been admitted under fourteen different names at facilities across the country.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Glass Animals',
      genre: 'horror',
      askingPrice: 370_000,
      scriptQuality: 6.8,
      conceptStrength: 8.4,
      logline: 'An entomologist studying a new invasive species realizes the insects have been studying her for just as long.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Second Growth',
      genre: 'horror',
      askingPrice: 290_000,
      scriptQuality: 7.1,
      conceptStrength: 8.3,
      logline: 'A forest service worker cataloguing timber damage discovers that trees in a remote section of old growth have begun growing toward a center point, away from the sun.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Shift',
      genre: 'horror',
      askingPrice: 315_000,
      scriptQuality: 7.4,
      conceptStrength: 8.0,
      logline: 'Night-shift workers at a distribution center begin reporting that their coworkers are identical to the day-shift team but do not recognize them by name.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Low Water',
      genre: 'horror',
      askingPrice: 270_000,
      scriptQuality: 7.6,
      conceptStrength: 7.8,
      logline: 'A drought exposes a section of reservoir bed that was supposedly never inhabited — and the farmhouse emerging from the mud still has interior furniture.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Resident',
      genre: 'horror',
      askingPrice: 295_000,
      scriptQuality: 7.3,
      conceptStrength: 8.2,
      logline: 'A hospice live-in caretaker realizes the patient she has been caring for over six months does not match the intake record she was given on day one.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Skin Deep',
      genre: 'horror',
      askingPrice: 325_000,
      scriptQuality: 7.0,
      conceptStrength: 8.4,
      logline: 'A dermatologist in a small coastal practice notices the same unusual lesion pattern appearing in the same location on unrelated patients who have never met.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Night Bloom',
      genre: 'horror',
      askingPrice: 285_000,
      scriptQuality: 7.5,
      conceptStrength: 7.9,
      logline: 'A botanist discovers a species that only flowers during a specific lunar phase — and that every documented discovery of it was followed by a local disappearance.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Cartwright House',
      genre: 'horror',
      askingPrice: 305_000,
      scriptQuality: 7.2,
      conceptStrength: 8.1,
      logline: 'A structural engineer assessing a condemned Victorian home discovers that the floor plan she keeps drawing does not match the building she keeps walking through.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Undertow',
      genre: 'horror',
      askingPrice: 260_000,
      scriptQuality: 7.7,
      conceptStrength: 7.6,
      logline: 'Open-water swimmers at a coastal training facility begin reporting something is pacing them from below — and the footage always cuts at the same distance.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Closed Season',
      genre: 'horror',
      askingPrice: 280_000,
      scriptQuality: 7.4,
      conceptStrength: 8.0,
      logline: 'A conservation officer stationed at a wildlife refuge during winter lockdown discovers the only species that has not retreated south is one she has never seen before.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Dry Rot',
      genre: 'horror',
      askingPrice: 255_000,
      scriptQuality: 7.6,
      conceptStrength: 7.7,
      logline: 'A home restoration contractor finds that every structural problem she repairs reappears overnight in a slightly different location.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Long Exposure',
      genre: 'horror',
      askingPrice: 330_000,
      scriptQuality: 7.1,
      conceptStrength: 8.5,
      logline: 'A wildlife photographer reviewing camera trap footage discovers that every frame shows the same animal — and the animal is always looking directly at the camera.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Mariner',
      genre: 'horror',
      askingPrice: 300_000,
      scriptQuality: 7.3,
      conceptStrength: 8.3,
      logline: 'A solo sailor attempting a circumnavigation realizes she is being shadowed by a vessel that does not appear on any tracking system, maintains her exact speed, and has no crew.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Deep Root',
      genre: 'horror',
      askingPrice: 250_000,
      scriptQuality: 7.5,
      conceptStrength: 7.8,
      logline: 'A utility crew excavating for a gas line in rural Nebraska hits a root system so vast it stops all equipment — and every tree above ground is dead.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Census',
      genre: 'horror',
      askingPrice: 345_000,
      scriptQuality: 6.9,
      conceptStrength: 8.6,
      logline: 'A historian researching a town legally dissolved in 1963 discovers census records that continue to list the same forty-seven names into the present day.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Mirror Lake',
      genre: 'horror',
      askingPrice: 360_000,
      scriptQuality: 7.0,
      conceptStrength: 8.7,
      logline: 'A limnologist studying unusual surface behavior on a remote mountain lake realizes it is not reflecting the sky above — but the one it was beneath before it existed.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Waiting Room',
      genre: 'horror',
      askingPrice: 310_000,
      scriptQuality: 7.4,
      conceptStrength: 8.2,
      logline: 'Patients in an unexplained mass-hypnagogic event in a hospital emergency room all describe the same figure standing in a room that does not exist on any floor plan.',
      expiresInWeeks: 3,
    },
    // ── ACTION ────────────────────────────────────────────────────────────────
    {
      id: createId('script'),
      title: 'Iron Collapse',
      genre: 'action',
      askingPrice: 650_000,
      scriptQuality: 7.0,
      conceptStrength: 7.5,
      logline: 'A structural engineer turned mercenary is hired to blow a corrupt government\'s showcase dam — after discovering her sister lives downstream.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Red Circuit',
      genre: 'action',
      askingPrice: 720_000,
      scriptQuality: 6.8,
      conceptStrength: 7.8,
      logline: 'A Europol operative goes rogue after discovering the terrorist network she has been tracking is run by her own agency.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Ground Zero Protocol',
      genre: 'action',
      askingPrice: 590_000,
      scriptQuality: 7.3,
      conceptStrength: 7.2,
      logline: 'A firefighter navigates a coordinated city-wide blackout to reach her trapped crew before it becomes permanent.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Terminal Point',
      genre: 'action',
      askingPrice: 680_000,
      scriptQuality: 7.1,
      conceptStrength: 7.4,
      logline: 'A former Secret Service agent has ninety minutes to stop an assassination plot unfolding inside a locked convention center.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Breakline',
      genre: 'action',
      askingPrice: 610_000,
      scriptQuality: 7.4,
      conceptStrength: 7.1,
      logline: 'A Marine reconnaissance team discovers a beachhead operation in neutral waters that no government will admit exists.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Compound',
      genre: 'action',
      askingPrice: 560_000,
      scriptQuality: 7.2,
      conceptStrength: 7.6,
      logline: 'A DEA strike team breaches a cartel compound only to find it cleared — and realizes they were meant to be there.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'High Altitude',
      genre: 'action',
      askingPrice: 640_000,
      scriptQuality: 7.0,
      conceptStrength: 7.3,
      logline: 'A civilian cargo pilot is forced into hostile airspace after her co-pilot turns out to be working for the other side.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Deadweight',
      genre: 'action',
      askingPrice: 700_000,
      scriptQuality: 6.9,
      conceptStrength: 7.9,
      logline: 'A deep-sea salvage expert is hired to recover a sunken vessel with a very much alive cargo that someone paid to disappear.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Extract',
      genre: 'action',
      askingPrice: 630_000,
      scriptQuality: 7.3,
      conceptStrength: 7.6,
      logline: 'A private security contractor in a failed state is hired to retrieve a kidnapped diplomat\'s aide — and discovers the aide is trying very hard not to be found.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Black Site',
      genre: 'action',
      askingPrice: 670_000,
      scriptQuality: 7.0,
      conceptStrength: 7.9,
      logline: 'A military attorney conducting a routine inspection of a classified facility discovers it is not the facility listed in her orders.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Fallthrough',
      genre: 'action',
      askingPrice: 580_000,
      scriptQuality: 7.4,
      conceptStrength: 7.5,
      logline: 'A special operations unit on a twenty-four-hour extraction mission discovers the intelligence that sent them has a seventy-two-hour lag, and the situation is already a disaster.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Retrieval',
      genre: 'action',
      askingPrice: 690_000,
      scriptQuality: 7.2,
      conceptStrength: 7.8,
      logline: 'A disgraced intelligence officer is offered full reinstatement in exchange for one job: retrieving a package from a city she was personally banned from entering.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Point of Entry',
      genre: 'action',
      askingPrice: 600_000,
      scriptQuality: 7.5,
      conceptStrength: 7.4,
      logline: 'A bomb disposal specialist is called to a device that is too simple to be a trap but too complex to be random — and discovers it was built to be found by her specifically.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Narrow Escape',
      genre: 'action',
      askingPrice: 550_000,
      scriptQuality: 7.1,
      conceptStrength: 7.7,
      logline: 'A professional courier carrying a package she was told not to open realizes mid-journey that the clients at both ends want the same thing: for her not to arrive.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Over the Wire',
      genre: 'action',
      askingPrice: 660_000,
      scriptQuality: 7.3,
      conceptStrength: 7.5,
      logline: 'A retired signals intelligence officer pulled back for a single intercept mission discovers the conversation she is asked to translate involves her own name.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Depth Charge',
      genre: 'action',
      askingPrice: 710_000,
      scriptQuality: 7.0,
      conceptStrength: 8.0,
      logline: 'A naval salvage team hired to recover an offshore platform realizes it was not decommissioned — it was being run off-book and is still very much active.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Contractor',
      genre: 'action',
      askingPrice: 620_000,
      scriptQuality: 7.4,
      conceptStrength: 7.6,
      logline: 'An independent logistics specialist hired to move untraceable cargo across three borders realizes each handoff is moving her closer to the origin, not away from it.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Perimeter',
      genre: 'action',
      askingPrice: 575_000,
      scriptQuality: 7.2,
      conceptStrength: 7.8,
      logline: 'A security detail protecting a tech executive for seventy-two hours realizes the threat they were briefed on was a distraction for something they were not told about at all.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Low Profile',
      genre: 'action',
      askingPrice: 645_000,
      scriptQuality: 7.5,
      conceptStrength: 7.3,
      logline: 'A former undercover agent living quietly in a coastal town is recognized by someone who should not be alive — and has forty-eight hours before that becomes operational.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Force Multiplier',
      genre: 'action',
      askingPrice: 695_000,
      scriptQuality: 6.9,
      conceptStrength: 7.9,
      logline: 'A military trainer embedded with an allied unit realizes the recruits she is training are significantly more experienced than any recruits have any business being.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Sweep',
      genre: 'action',
      askingPrice: 560_000,
      scriptQuality: 7.3,
      conceptStrength: 7.7,
      logline: 'A law enforcement tactical team clears a building floor by floor only to discover the building has more floors than it was permitted to construct.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Hard Target',
      genre: 'action',
      askingPrice: 680_000,
      scriptQuality: 7.1,
      conceptStrength: 7.6,
      logline: 'A protection specialist realizes the threat on her client\'s life is not a foreign actor but someone on the inside of the protection detail — possibly herself.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Blackout Protocol',
      genre: 'action',
      askingPrice: 605_000,
      scriptQuality: 7.4,
      conceptStrength: 8.1,
      logline: 'A power grid security analyst watching a rolling blackout spread across a city map realizes the pattern is not random — it is a message being broadcast from inside the grid.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Threshold',
      genre: 'action',
      askingPrice: 625_000,
      scriptQuality: 7.0,
      conceptStrength: 7.8,
      logline: 'A border enforcement officer discovers a network of tunnels that does not match any known smuggling route — because it was built to move people out of the country, not in.',
      expiresInWeeks: 2,
    },
    // ── COMEDY ────────────────────────────────────────────────────────────────
    {
      id: createId('script'),
      title: 'Plus One',
      genre: 'comedy',
      askingPrice: 280_000,
      scriptQuality: 7.6,
      conceptStrength: 7.0,
      logline: 'A professional wedding crasher accidentally gets hired by the bride\'s family to keep the groom\'s ex away from the reception.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Understudy',
      genre: 'comedy',
      askingPrice: 320_000,
      scriptQuality: 7.3,
      conceptStrength: 7.4,
      logline: 'When a famous life coach enters witness protection, the government assigns a chronically unprepared agent to impersonate him.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Corporate Retreat',
      genre: 'comedy',
      askingPrice: 260_000,
      scriptQuality: 7.5,
      conceptStrength: 6.9,
      logline: 'Seven employees from competing departments are stranded at a mandatory team-building weekend when a snowstorm closes the mountain.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Forty-Eight Hours',
      genre: 'comedy',
      askingPrice: 300_000,
      scriptQuality: 7.8,
      conceptStrength: 7.2,
      logline: 'Two ex-spouses, both divorce attorneys, must cooperate after their daughter accidentally registers them as a team in a national trivia tournament.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Reserve List',
      genre: 'comedy',
      askingPrice: 340_000,
      scriptQuality: 7.1,
      conceptStrength: 7.8,
      logline: 'A mild-mannered librarian discovers she has been on the CIA\'s emergency recruitment roster for twenty-two years and her number finally came up.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Exit Interview',
      genre: 'comedy',
      askingPrice: 245_000,
      scriptQuality: 7.4,
      conceptStrength: 7.1,
      logline: 'A mid-level office drone is tasked with firing forty people in one week, and every single one is more competent than him.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Table for Twelve',
      genre: 'comedy',
      askingPrice: 270_000,
      scriptQuality: 7.7,
      conceptStrength: 6.8,
      logline: 'A critic who has never given more than two stars agrees to plan her estranged sister\'s rehearsal dinner.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Open Floor Plan',
      genre: 'comedy',
      askingPrice: 290_000,
      scriptQuality: 7.2,
      conceptStrength: 7.5,
      logline: 'A reclusive novelist forced to live in a co-working space during renovations accidentally becomes the social center of an entire startup floor.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Interim',
      genre: 'comedy',
      askingPrice: 255_000,
      scriptQuality: 7.8,
      conceptStrength: 7.0,
      logline: 'A retired judge is asked to sit in on a single case as a favor — and the case turns out to be his own parking dispute from 1987.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Mutual Assured Awkwardness',
      genre: 'comedy',
      askingPrice: 310_000,
      scriptQuality: 7.5,
      conceptStrength: 7.3,
      logline: 'Two former best friends who had a spectacular falling out are both hired as consultants on the same project and must pretend they have never met.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Full Disclosure',
      genre: 'comedy',
      askingPrice: 285_000,
      scriptQuality: 7.9,
      conceptStrength: 7.1,
      logline: 'A notoriously private tech CEO accidentally sends a deeply personal email to the entire company mailing list and must manage the fallout while everyone starts being kind to him.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Temp',
      genre: 'comedy',
      askingPrice: 235_000,
      scriptQuality: 7.6,
      conceptStrength: 7.5,
      logline: 'A temp worker placed in a law firm accidentally attends the wrong orientation and spends two weeks as a junior partner before anyone notices.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Wrong Number',
      genre: 'comedy',
      askingPrice: 265_000,
      scriptQuality: 7.4,
      conceptStrength: 7.8,
      logline: 'A case of mistaken identity sends a mild-mannered accountant to a conference he was not invited to, where everyone treats him as a keynote speaker and won\'t let him leave.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Promotion',
      genre: 'comedy',
      askingPrice: 275_000,
      scriptQuality: 7.7,
      conceptStrength: 7.2,
      logline: 'A mid-level employee who has never wanted to be promoted is accidentally put on the fast track by a well-meaning HR system and must keep failing upward while pretending to try.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'On the Record',
      genre: 'comedy',
      askingPrice: 295_000,
      scriptQuality: 7.3,
      conceptStrength: 7.6,
      logline: 'A newspaper editor trying to kill a story about his own office accidentally generates the most viral news cycle in the paper\'s history — while attempting to go on vacation.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Best Case Scenario',
      genre: 'comedy',
      askingPrice: 315_000,
      scriptQuality: 7.6,
      conceptStrength: 6.9,
      logline: 'A chronically pessimistic disaster-preparedness coordinator falls in love with an optimist whose elaborate vacation plans keep accidentally exceeding all expectations.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Advisor',
      genre: 'comedy',
      askingPrice: 250_000,
      scriptQuality: 7.2,
      conceptStrength: 7.4,
      logline: 'A recently divorced life coach whose own life is thoroughly unmanaged is hired by an overwhelmed executive family to bring order to their household.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Mandatory Fun',
      genre: 'comedy',
      askingPrice: 240_000,
      scriptQuality: 7.5,
      conceptStrength: 7.0,
      logline: 'An HR director at a mid-sized company is required by headquarters to implement a mandatory wellness program that she personally finds completely meaningless.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Handoff',
      genre: 'comedy',
      askingPrice: 270_000,
      scriptQuality: 7.8,
      conceptStrength: 6.8,
      logline: 'Two rival real estate agents both accept the same listing at the same open house from the same confused elderly seller, and try to outmaneuver each other while remaining polite.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Overlap',
      genre: 'comedy',
      askingPrice: 285_000,
      scriptQuality: 7.1,
      conceptStrength: 7.7,
      logline: 'An organizational efficiency consultant hired to restructure a company realizes she already recommended the exact opposite restructuring to this client six years ago.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Guest Speaker',
      genre: 'comedy',
      askingPrice: 305_000,
      scriptQuality: 7.4,
      conceptStrength: 7.3,
      logline: 'A professor invited to give a keynote is told on arrival that the conference changed its theme — and that she will need to speak on a subject she famously disagrees with.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Paper Trail',
      genre: 'comedy',
      askingPrice: 225_000,
      scriptQuality: 7.7,
      conceptStrength: 7.6,
      logline: 'A city clerk trying to process a routine permit request uncovers a zoning loop that technically makes the entire downtown a legally uninhabitable wetland.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Working Title',
      genre: 'comedy',
      askingPrice: 260_000,
      scriptQuality: 7.3,
      conceptStrength: 7.1,
      logline: 'Two documentary crews assigned to profile the same small business owner show up on the same day and, after two minutes of arguing, decide to just film each other.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Referral',
      genre: 'comedy',
      askingPrice: 330_000,
      scriptQuality: 7.0,
      conceptStrength: 7.9,
      logline: 'A therapist\'s clients start referring each other so aggressively that her waitlist becomes a social network, her social network becomes a crisis, and the crisis becomes her next case.',
      expiresInWeeks: 3,
    },
    // ── ANIMATION ─────────────────────────────────────────────────────────────
    {
      id: createId('script'),
      title: 'Rust and Bloom',
      genre: 'animation',
      askingPrice: 380_000,
      scriptQuality: 7.9,
      conceptStrength: 8.2,
      logline: 'A maintenance robot assigned to a post-human greenhouse discovers the plants it tends have developed rudimentary language.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Cartographer',
      genre: 'animation',
      askingPrice: 350_000,
      scriptQuality: 7.6,
      conceptStrength: 8.0,
      logline: 'A young mapmaker\'s drawings begin predicting disasters before they happen, and she must decide who deserves to see the next one.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Copper Wings',
      genre: 'animation',
      askingPrice: 420_000,
      scriptQuality: 7.4,
      conceptStrength: 7.8,
      logline: 'A clockwork owl built to guard a palace archive develops curiosity and helps a young thief uncover the empire\'s buried history.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Stormwarden',
      genre: 'animation',
      askingPrice: 460_000,
      scriptQuality: 7.2,
      conceptStrength: 8.3,
      logline: 'A storm-chasing duo — a girl and her weather-reading grandmother\'s ghost — protect their coastal island from a season of supernatural hurricanes.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Last Menagerie',
      genre: 'animation',
      askingPrice: 400_000,
      scriptQuality: 7.8,
      conceptStrength: 7.6,
      logline: 'The caretaker of the universe\'s last magical creature preserve must choose which animals survive when the funding is cut.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Drift',
      genre: 'animation',
      askingPrice: 340_000,
      scriptQuality: 7.5,
      conceptStrength: 8.1,
      logline: 'An amnesiac cloud spirit pieces together her identity from the weather memories she scattered across the world.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Ember Root',
      genre: 'animation',
      askingPrice: 390_000,
      scriptQuality: 7.3,
      conceptStrength: 7.9,
      logline: 'A young fire-tender in a world where flames are the only source of heat must retrieve a stolen ember from a frozen city.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Glass City',
      genre: 'animation',
      askingPrice: 430_000,
      scriptQuality: 7.0,
      conceptStrength: 8.4,
      logline: 'After all the adults in a city fall into an unexplained sleep, its children must keep everything running until someone finds a cure.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Weighmaster',
      genre: 'animation',
      askingPrice: 410_000,
      scriptQuality: 7.7,
      conceptStrength: 8.0,
      logline: 'A scale-keeper in a kingdom where weight determines worth discovers his scales have been secretly miscalibrated for a century — and who benefits.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Cloudwright',
      genre: 'animation',
      askingPrice: 445_000,
      scriptQuality: 7.4,
      conceptStrength: 8.4,
      logline: 'A cloud sculptor who shapes weather patterns for the kingdom discovers that the perfect storm she built has been stolen and redirected toward the capital.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Ferryman\'s Daughter',
      genre: 'animation',
      askingPrice: 375_000,
      scriptQuality: 7.8,
      conceptStrength: 7.9,
      logline: 'A young ferryman apprentice discovers the river she crosses daily leads to different shores depending on who is crossing, and nobody will tell her why.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Paper Army',
      genre: 'animation',
      askingPrice: 360_000,
      scriptQuality: 7.5,
      conceptStrength: 8.1,
      logline: 'A schoolgirl who can make origami animals come to life must use her limited paper supply to protect her village from an army of very well-funded soldiers.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Mapmaker\'s Compass',
      genre: 'animation',
      askingPrice: 395_000,
      scriptQuality: 7.6,
      conceptStrength: 8.3,
      logline: 'A young explorer receives a compass that points not to north but to what the holder needs most — and follows it into danger to help the people she loves.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Nightwatchman',
      genre: 'animation',
      askingPrice: 355_000,
      scriptQuality: 7.9,
      conceptStrength: 7.7,
      logline: 'A small town\'s nighttime protector is a shy, perpetually exhausted star that would like to take one night off but cannot find a replacement.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Salt Merchant',
      genre: 'animation',
      askingPrice: 415_000,
      scriptQuality: 7.3,
      conceptStrength: 8.5,
      logline: 'A young salt merchant in a world where salt can preserve memories discovers a pouch that contains the most dangerous memory ever extracted.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Tidal',
      genre: 'animation',
      askingPrice: 440_000,
      scriptQuality: 7.1,
      conceptStrength: 8.6,
      logline: 'A lighthouse keeper\'s daughter discovers that the lighthouse\'s light does not help ships navigate — it keeps something very large from coming ashore.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Inkwright',
      genre: 'animation',
      askingPrice: 405_000,
      scriptQuality: 7.7,
      conceptStrength: 8.2,
      logline: 'An apprentice scribe discovers that anything she writes in the ancient ink becomes true — and that the previous apprentice left instructions she was not supposed to find.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Hollow Mountain',
      genre: 'animation',
      askingPrice: 455_000,
      scriptQuality: 7.2,
      conceptStrength: 8.7,
      logline: 'A young geologist\'s apprentice discovers a mountain range that is entirely hollow, inhabited, and has been hiding from the surface world for three hundred years.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Folded Map',
      genre: 'animation',
      askingPrice: 380_000,
      scriptQuality: 7.5,
      conceptStrength: 8.3,
      logline: 'A cartography student discovers her late mentor\'s final map is of a place that was never drawn because it moves — and has been avoiding mapmakers for centuries.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Kindled',
      genre: 'animation',
      askingPrice: 430_000,
      scriptQuality: 7.4,
      conceptStrength: 8.1,
      logline: 'A fire-breathing girl in a world where fire was outlawed forty years ago discovers that the law was not a safety measure — it was a containment strategy.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Warden\'s Apprentice',
      genre: 'animation',
      askingPrice: 365_000,
      scriptQuality: 7.8,
      conceptStrength: 7.8,
      logline: 'A young girl inherits the job of forest warden, which turns out to involve mediating disputes between species she did not know existed.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Drift Line',
      genre: 'animation',
      askingPrice: 395_000,
      scriptQuality: 7.1,
      conceptStrength: 8.4,
      logline: 'Two young lighthouse keepers on separate islands discover they can communicate through the fog — and that something in the fog has been listening for years.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Dreamer\'s Atlas',
      genre: 'animation',
      askingPrice: 420_000,
      scriptQuality: 7.6,
      conceptStrength: 8.0,
      logline: 'A girl who maps the recurring dreams of her village realizes the dreams are not random — they are a warning system, and they all share the same landmark.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Iron Bloom',
      genre: 'animation',
      askingPrice: 435_000,
      scriptQuality: 7.3,
      conceptStrength: 8.5,
      logline: 'In a world where plants are made of metal and metal rusts, a young metallurgist apprentice discovers that the rare plant that never rusts may be the key to saving everything.',
      expiresInWeeks: 3,
    },
    // ── DOCUMENTARY ───────────────────────────────────────────────────────────
    {
      id: createId('script'),
      title: 'The Archive',
      genre: 'documentary',
      askingPrice: 180_000,
      scriptQuality: 8.2,
      conceptStrength: 7.4,
      logline: 'An investigation into a film preservation vault that holds four thousand movies no one is legally allowed to screen.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Controlled Burn',
      genre: 'documentary',
      askingPrice: 160_000,
      scriptQuality: 7.9,
      conceptStrength: 7.1,
      logline: 'Three career wildland firefighters reflect on a season that changed everything they believed about fire management.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Quiet Hours',
      genre: 'documentary',
      askingPrice: 145_000,
      scriptQuality: 8.4,
      conceptStrength: 6.9,
      logline: 'A year inside a maximum-security prison\'s end-of-life ward, where inmates serve their final months in a hospice unit run by fellow prisoners.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Signal Lost',
      genre: 'documentary',
      askingPrice: 155_000,
      scriptQuality: 7.7,
      conceptStrength: 7.3,
      logline: 'The untold story of seven independent radio stations that stayed on air during a major city\'s complete power grid collapse.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Undercurrent',
      genre: 'documentary',
      askingPrice: 170_000,
      scriptQuality: 8.0,
      conceptStrength: 7.2,
      logline: 'Following a coalition of fishing communities fighting a biotech firm\'s offshore operation, told across four years of legal battles.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'One Block',
      genre: 'documentary',
      askingPrice: 135_000,
      scriptQuality: 8.1,
      conceptStrength: 6.8,
      logline: 'A year-long portrait of a single city block, its fourteen buildings, and the two hundred and twenty people who call it home.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Legacy Weight',
      genre: 'documentary',
      askingPrice: 165_000,
      scriptQuality: 7.6,
      conceptStrength: 7.5,
      logline: 'Three Olympic-caliber athletes discuss life after the Games, performance pressure, and what their sports ultimately cost them.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Long Haul',
      genre: 'documentary',
      askingPrice: 150_000,
      scriptQuality: 7.8,
      conceptStrength: 7.0,
      logline: 'Coast-to-coast with five long-distance truckers over one winter, examining what happens to communities when infrastructure quietly collapses.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Exit Interview',
      genre: 'documentary',
      askingPrice: 175_000,
      scriptQuality: 8.0,
      conceptStrength: 7.3,
      logline: 'Sixteen retiring executives from across American industry sit for candid final interviews the week before they leave power, saying things they never said when it mattered.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Night Shift',
      genre: 'documentary',
      askingPrice: 145_000,
      scriptQuality: 8.3,
      conceptStrength: 7.0,
      logline: 'A year-long portrait of the overnight staff at a major urban hospital — the nurses, janitors, security guards, and patients who inhabit the building when no one is watching.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Permanent Record',
      genre: 'documentary',
      askingPrice: 160_000,
      scriptQuality: 7.8,
      conceptStrength: 7.5,
      logline: 'A retired archivist spent forty years collecting records that governments threw away. What she found, and what she did with it, is the subject of this film.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Return',
      genre: 'documentary',
      askingPrice: 140_000,
      scriptQuality: 8.1,
      conceptStrength: 6.9,
      logline: 'Three formerly incarcerated individuals return to the communities they left and attempt, across four seasons, to be accepted as the people they have become.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Builders',
      genre: 'documentary',
      askingPrice: 155_000,
      scriptQuality: 7.6,
      conceptStrength: 7.2,
      logline: 'Following the welders, electricians, and ironworkers constructing a six-billion-dollar bridge in a region that has not had a major project in a generation.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Under the Line',
      genre: 'documentary',
      askingPrice: 135_000,
      scriptQuality: 8.2,
      conceptStrength: 6.7,
      logline: 'A candid examination of life just below the federal poverty line, told across twelve months in four households sharing the same zip code.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Last Session',
      genre: 'documentary',
      askingPrice: 170_000,
      scriptQuality: 7.9,
      conceptStrength: 7.4,
      logline: 'Three psychiatrists retiring this year each sit for a final extended session with the filmmaker, reflecting on what decades of listening to other people\'s lives has done to their own.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Negotiation',
      genre: 'documentary',
      askingPrice: 150_000,
      scriptQuality: 7.7,
      conceptStrength: 7.6,
      logline: 'A documentary crew is granted access to an ongoing labor negotiation between a major transit authority and its union — and films every session for six weeks.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Flood Line',
      genre: 'documentary',
      askingPrice: 145_000,
      scriptQuality: 8.0,
      conceptStrength: 7.1,
      logline: 'Following seven families from the same rural county who lost their homes to flooding, tracking what happens to a community when recovery aid is systematically misallocated.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Open Season',
      genre: 'documentary',
      askingPrice: 130_000,
      scriptQuality: 8.3,
      conceptStrength: 6.8,
      logline: 'A year inside a public defender\'s office in a major American city — one of the most underfunded corners of the legal system — and the people who stay anyway.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Seed Library',
      genre: 'documentary',
      askingPrice: 140_000,
      scriptQuality: 7.8,
      conceptStrength: 7.3,
      logline: 'A group of volunteers maintains a seed bank in an abandoned Montana vault, preserving three thousand crop varieties that commercial agriculture has abandoned.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'Terminal Velocity',
      genre: 'documentary',
      askingPrice: 165_000,
      scriptQuality: 7.5,
      conceptStrength: 7.7,
      logline: 'An investigation into five aviation near-misses that were each reported, each investigated, and each corrected in ways that made the next incident more likely.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'The Count',
      genre: 'documentary',
      askingPrice: 125_000,
      scriptQuality: 7.9,
      conceptStrength: 6.9,
      logline: 'A look inside the census process from the perspective of the enumerators — the temporary federal workers who knock on one hundred and forty million doors.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Backroom',
      genre: 'documentary',
      askingPrice: 145_000,
      scriptQuality: 7.6,
      conceptStrength: 7.4,
      logline: 'A filmmaker spends one election cycle inside a local city council race in a mid-sized American city, following every meeting, hallway conversation, and compromise.',
      expiresInWeeks: 3,
    },
    {
      id: createId('script'),
      title: 'The Weight of Nothing',
      genre: 'documentary',
      askingPrice: 135_000,
      scriptQuality: 8.1,
      conceptStrength: 7.0,
      logline: 'An examination of homelessness in three American cities told through the perspective of outreach workers — not the people they serve, but the people who serve.',
      expiresInWeeks: 2,
    },
    {
      id: createId('script'),
      title: 'Before the Lights Go Out',
      genre: 'documentary',
      askingPrice: 120_000,
      scriptQuality: 7.7,
      conceptStrength: 7.2,
      logline: 'Seven small-town newspapers, each with under two thousand subscribers, navigating the last years of local print journalism.',
      expiresInWeeks: 2,
    },
  ];
}

export function createSeedRivals(): RivalStudio[] {
  return [
    {
      id: createId('rival'),
      name: 'Meridian Pictures',
      personality: 'prestigeHunter',
      studioHeat: 61,
      activeReleases: [],
      upcomingReleases: [],
      lockedTalentIds: [],
      memory: createInitialRivalMemory('prestigeHunter'),
    },
    {
      id: createId('rival'),
      name: 'Apex Global',
      personality: 'blockbusterFactory',
      studioHeat: 74,
      activeReleases: [],
      upcomingReleases: [],
      lockedTalentIds: [],
      memory: createInitialRivalMemory('blockbusterFactory'),
    },
    {
      id: createId('rival'),
      name: 'Neon Slate',
      personality: 'genreSpecialist',
      studioHeat: 56,
      activeReleases: [],
      upcomingReleases: [],
      lockedTalentIds: [],
      memory: createInitialRivalMemory('genreSpecialist'),
    },
    {
      id: createId('rival'),
      name: 'Harbor Road',
      personality: 'streamingFirst',
      studioHeat: 52,
      activeReleases: [],
      upcomingReleases: [],
      lockedTalentIds: [],
      memory: createInitialRivalMemory('streamingFirst'),
    },
    {
      id: createId('rival'),
      name: 'Freehold Films',
      personality: 'scrappyUpstart',
      studioHeat: 41,
      activeReleases: [],
      upcomingReleases: [],
      lockedTalentIds: [],
      memory: createInitialRivalMemory('scrappyUpstart'),
    },
  ];
}

