import type { DecisionItem, MovieProject } from '../types';
import { createId } from '../id';

export function createSeedProjects(): MovieProject[] {
  return [
    {
      id: createId('project'),
      title: 'Night Ledger',
      genre: 'thriller',
      phase: 'production',
      budget: {
        ceiling: 24_000_000,
        aboveTheLine: 7_800_000,
        belowTheLine: 11_400_000,
        postProduction: 3_200_000,
        contingency: 1_600_000,
        overrunRisk: 0.38,
        actualSpend: 9_500_000,
      },
      budgetPlan: {
        directorPlanned: 2_400_000,
        castPlannedTotal: 3_600_000,
        castPlannedActor: 3_600_000,
        castPlannedActress: 0,
      },
      castRequirements: {
        actorCount: 1,
        actressCount: 0,
      },
      scriptQuality: 7.4,
      conceptStrength: 7.1,
      editorialScore: 5,
      postPolishPasses: 0,
      directorId: null,
      castIds: [],
      productionStatus: 'onTrack',
      scheduledWeeksRemaining: 12,
      hypeScore: 33,
      marketingBudget: 2_000_000,
      releaseWindow: null,
      releaseWeek: null,
      releaseWeekLocked: false,
      distributionPartner: null,
      studioRevenueShare: 0.52,
      projectedROI: 1.52,
      openingWeekendGross: null,
      weeklyGrossHistory: [],
      releaseWeeksRemaining: 0,
      releaseResolved: false,
      finalBoxOffice: null,
      criticalScore: null,
      audienceScore: null,
      awardsNominations: 0,
      awardsWins: 0,
      festivalStatus: 'none',
      festivalTarget: null,
      festivalSubmissionWeek: null,
      festivalResolutionWeek: null,
      festivalBuzz: 0,
      prestige: 42,
      commercialAppeal: 68,
      originality: 57,
      controversy: 28,
      franchiseId: null,
      franchiseEpisode: null,
      sequelToProjectId: null,
      franchiseCarryoverHype: 0,
      franchiseStrategy: 'none',
      greenlightApproved: true,
      greenlightWeek: 0,
      greenlightFeePaid: 0,
      greenlightLockedCeiling: 24_000_000,
      sentBackForRewriteCount: 0,
      testScreeningCompleted: false,
      testScreeningWeek: null,
      testScreeningCriticalLow: null,
      testScreeningCriticalHigh: null,
      testScreeningAudienceSentiment: null,
      reshootCount: 0,
      trackingProjectionOpening: null,
      trackingConfidence: null,
      trackingLeverageAmount: 0,
      trackingSettled: false,
      merchandiseWeeksRemaining: 0,
      merchandiseWeeklyRevenue: 0,
      adaptedFromIpId: null,
    },
    {
      id: createId('project'),
      title: 'Blue Ember',
      genre: 'drama',
      phase: 'development',
      budget: {
        ceiling: 12_000_000,
        aboveTheLine: 3_800_000,
        belowTheLine: 5_400_000,
        postProduction: 1_700_000,
        contingency: 1_100_000,
        overrunRisk: 0.26,
        actualSpend: 500_000,
      },
      budgetPlan: {
        directorPlanned: 1_200_000,
        castPlannedTotal: 2_100_000,
        castPlannedActor: 2_100_000,
        castPlannedActress: 0,
      },
      castRequirements: {
        actorCount: 1,
        actressCount: 0,
      },
      scriptQuality: 8.1,
      conceptStrength: 6.8,
      editorialScore: 5,
      postPolishPasses: 0,
      directorId: null,
      castIds: [],
      productionStatus: 'onTrack',
      scheduledWeeksRemaining: 18,
      hypeScore: 18,
      marketingBudget: 0,
      releaseWindow: null,
      releaseWeek: null,
      releaseWeekLocked: false,
      distributionPartner: null,
      studioRevenueShare: 0.52,
      projectedROI: 1.18,
      openingWeekendGross: null,
      weeklyGrossHistory: [],
      releaseWeeksRemaining: 0,
      releaseResolved: false,
      finalBoxOffice: null,
      criticalScore: null,
      audienceScore: null,
      awardsNominations: 0,
      awardsWins: 0,
      festivalStatus: 'none',
      festivalTarget: null,
      festivalSubmissionWeek: null,
      festivalResolutionWeek: null,
      festivalBuzz: 0,
      prestige: 72,
      commercialAppeal: 37,
      originality: 64,
      controversy: 14,
      franchiseId: null,
      franchiseEpisode: null,
      sequelToProjectId: null,
      franchiseCarryoverHype: 0,
      franchiseStrategy: 'none',
      greenlightApproved: false,
      greenlightWeek: null,
      greenlightFeePaid: 0,
      greenlightLockedCeiling: null,
      sentBackForRewriteCount: 0,
      testScreeningCompleted: false,
      testScreeningWeek: null,
      testScreeningCriticalLow: null,
      testScreeningCriticalHigh: null,
      testScreeningAudienceSentiment: null,
      reshootCount: 0,
      trackingProjectionOpening: null,
      trackingConfidence: null,
      trackingLeverageAmount: 0,
      trackingSettled: false,
      merchandiseWeeksRemaining: 0,
      merchandiseWeeklyRevenue: 0,
      adaptedFromIpId: null,
    },
  ];
}

export function createOpeningDecisions(): DecisionItem[] {
  return [
    {
      id: createId('decision'),
      projectId: null,
      title: 'First Call: Script Doctor on Night Ledger',
      body: 'Welcome to the chair. Night Ledger is your flagship thriller already in production, with script quality at 7.4. A script doctor is offering a two-week polish sprint for $360K that could push quality to 8.2 and improve awards and critic upside. Decisions like this expire if you advance too many weeks without resolving them.',
      weeksUntilExpiry: 3,
      category: 'creative',
      options: [
        {
          id: createId('option'),
          label: 'Fund the Sprint',
          preview: 'Script quality +0.8 - brings Night Ledger to 8.2, a strong prestige threshold.',
          cashDelta: -360_000,
          scriptQualityDelta: 0.8,
          hypeDelta: 2,
          criticsDelta: 1,
        },
        {
          id: createId('option'),
          label: 'Pass for Now',
          preview: 'Save $360K. Night Ledger stays at current quality.',
          cashDelta: 0,
          scriptQualityDelta: 0,
          hypeDelta: -1,
        },
      ],
    },
  ];
}
