import type { EventTemplate } from '../../types';

export const lateCycleEvents: EventTemplate[] = [
{
      id: 'crew-retention-bonus',
      category: 'operations',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      title: 'Crew Retention Bonus Pool',
      decisionTitle: 'Crew Retention Bonus Pool',
      body: 'Department heads warn that fatigue is rising and senior crew could walk before lock.',
      cooldownWeeks: 11,
      baseWeight: 0.78,
      minWeek: 10,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Crew Retention Bonus Pool',
        body: projectTitle
          ? `${projectTitle} is at risk of losing key crew unless retention terms improve this week.`
          : 'Key crew may leave unless retention terms improve this week.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund Full Bonus Pool',
            preview: 'Stabilizes set morale and keeps pace.',
            cashDelta: -220_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            talentRepDelta: 2,
            audienceDelta: 1,
            scheduleDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Cover Key Departments Only',
            preview: 'Cheaper partial solution.',
            cashDelta: -110_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            talentRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Current Terms',
            preview: 'No cash outlay. Turnover risk rises.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            talentRepDelta: -2,
            scheduleDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'third-act-clarity-pass',
      category: 'creative',
      scope: 'project',
      targetPhases: ['postProduction'],
      title: 'Third Act Clarity Pass',
      decisionTitle: 'Third Act Clarity Pass',
      body: 'Late cuts reveal confusion in the final act. There is still time for a targeted fix.',
      cooldownWeeks: 12,
      baseWeight: 0.7,
      minWeek: 11,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Third Act Clarity Pass',
        body: projectTitle
          ? `${projectTitle} can run a late clarity pass to tighten the ending before final lock.`
          : 'You can run a late clarity pass to tighten the ending before final lock.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Run Pickup And Rewrite Pass',
            preview: 'High-cost repair with strongest upside.',
            cashDelta: -260_000,
            scriptQualityDelta: 0.3,
            hypeDelta: 0,
            criticsDelta: 2,
            scheduleDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'ADR And Edit Tightening',
            preview: 'Moderate improvement for lower spend.',
            cashDelta: -90_000,
            scriptQualityDelta: 0.1,
            hypeDelta: 0,
            criticsDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Ship Current Cut',
            preview: 'Protect schedule and cash.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            audienceDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'industry-analyst-day',
      category: 'marketing',
      scope: 'studio',
      title: 'Industry Analyst Day',
      decisionTitle: 'Industry Analyst Day',
      body: 'Trade analysts ask for direct studio briefings on your slate quality and long-term strategy.',
      cooldownWeeks: 20,
      baseWeight: 0.66,
      minWeek: 16,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'marketing',
        title: 'Industry Analyst Day',
        body: 'How you present the slate this quarter will shape distributor confidence for upcoming negotiations.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Host Full Showcase',
            preview: 'Costs cash. Builds broad confidence.',
            cashDelta: -190_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            distributorRepDelta: 2,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Run Private Briefings',
            preview: 'Cheaper and focused.',
            cashDelta: -70_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Skip This Cycle',
            preview: 'No spend. Leaves narrative to others.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
            distributorRepDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'guild-training-initiative',
      category: 'operations',
      scope: 'studio',
      title: 'Guild Training Initiative',
      decisionTitle: 'Guild Training Initiative',
      body: 'Guild reps invite the studio to co-fund a new below-the-line training pipeline.',
      cooldownWeeks: 26,
      baseWeight: 0.6,
      minWeek: 20,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'operations',
        title: 'Guild Training Initiative',
        body: 'It is not mandatory, but the industry will remember who helped staff the next generation.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Sponsor At Lead Tier',
            preview: 'Strong long-term goodwill play.',
            cashDelta: -240_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
            talentRepDelta: 3,
          },
          {
            id: idFactory('opt'),
            label: 'Join As Co-Funder',
            preview: 'Balanced contribution.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: 1,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Decline Participation',
            preview: 'Save cash now. Creates labor friction.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            talentRepDelta: -2,
            audienceDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'release-calendar-jam',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      title: 'Release Calendar Jam',
      decisionTitle: 'Release Calendar Jam',
      body: 'Two similar titles moved into your corridor and exhibitors are signaling tighter screen access.',
      cooldownWeeks: 13,
      baseWeight: 0.76,
      minWeek: 14,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Release Calendar Jam',
        body: projectTitle
          ? `${projectTitle} now shares a crowded window and your booking leverage is being tested.`
          : 'Your release now shares a crowded window and booking leverage is being tested.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Buy Premium Screens',
            preview: 'Expensive defense, keeps pressure on rivals.',
            cashDelta: -300_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            distributorRepDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Shift One Week',
            preview: 'Moderate cost, cleaner lane.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            audienceDelta: 1,
            releaseWeekShift: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Current Plan',
            preview: 'No spend, weaker leverage.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            distributorRepDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'library-restoration-package',
      category: 'finance',
      scope: 'studio',
      title: 'Library Restoration Package',
      decisionTitle: 'Library Restoration Package',
      body: 'A restoration vendor offers a discounted package to remaster catalog titles and relaunch them in premium formats.',
      cooldownWeeks: 30,
      baseWeight: 0.55,
      minWeek: 22,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Library Restoration Package',
        body: 'Catalog strategy will not move this quarter cash flow, but it can change how the studio is valued long-term.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Restore Full Catalog Set',
            preview: 'Largest cost, strongest legacy signal.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 2,
            audienceDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Restore Select Titles',
            preview: 'Moderate spend, moderate upside.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 1,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Pass This Cycle',
            preview: 'No cost now.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'festival-jury-lobby-window',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      title: 'Festival Jury Lobby Window',
      decisionTitle: 'Festival Jury Lobby Window',
      body: 'Publicists present a narrow outreach window to shape early festival juror sentiment.',
      cooldownWeeks: 14,
      baseWeight: 0.68,
      minWeek: 12,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Festival Jury Lobby Window',
        body: projectTitle
          ? `Publicists believe ${projectTitle} can gain festival leverage with immediate targeted outreach.`
          : 'Publicists believe this title can gain festival leverage with immediate targeted outreach.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Run Full Outreach Push',
            preview: 'Highest influence, highest spend.',
            cashDelta: -150_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 2,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Keep It Low-Key',
            preview: 'Lower spend, controlled upside.',
            cashDelta: -60_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Avoid Lobbying',
            preview: 'No spend, no narrative control.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
            talentRepDelta: 1,
          },
        ],
      }),
    },
];
