import type { EventTemplate } from '../../types';

export const productionPostEvents: EventTemplate[] = [
{
      id: 'director-vision-clash',
      category: 'creative',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Director-DP Standoff',
      decisionTitle: 'Director-DP Standoff',
      body: 'Your director and cinematographer are deadlocked over visual approach three weeks into principal photography.',
      cooldownWeeks: 5,
      baseWeight: 1.1,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Director-DP Standoff',
        body: projectTitle
          ? `Director and DP on ${projectTitle} are at an impasse over visual language. Both have valid arguments.`
          : 'Director and DP are at an impasse over visual language. Both have valid arguments.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Back The Director',
            preview: 'Preserves creative coherence. Costs you a DP relationship.',
            cashDelta: 0,
            scriptQualityDelta: 0.2,
            hypeDelta: -1,
            talentRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Back The DP',
            preview: 'More commercial result. Director friction.',
            cashDelta: 0,
            scriptQualityDelta: -0.1,
            hypeDelta: 2,
            talentRepDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Bring In A Mediator',
            preview: 'Costs cash. Resolves cleanly.',
            cashDelta: -120_000,
            scriptQualityDelta: 0.1,
            hypeDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'cold-audience-test',
      category: 'creative',
      scope: 'project',
      targetPhases: ['postProduction'],
      title: 'Cold Read Returns',
      decisionTitle: 'Cold Read Returns',
      body: 'An unannounced civilian test screening returns scores that contradict your internal tracking.',
      cooldownWeeks: 5,
      baseWeight: 1.05,
      minWeek: 5,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Cold Read Returns',
        body: projectTitle
          ? `An unannounced civilian screening of ${projectTitle} returned unexpected scores. Internal tracking had it wrong.`
          : 'An unannounced civilian screening returned unexpected scores. Internal tracking had it wrong.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Order A Targeted Recut',
            preview: 'Costs money and time. Fixes the problem.',
            cashDelta: -230_000,
            scriptQualityDelta: 0.3,
            hypeDelta: 0,
          },
          {
            id: idFactory('opt'),
            label: 'Dismiss The Data',
            preview: 'Bold stance. May be right.',
            cashDelta: 0,
            scriptQualityDelta: -0.1,
            hypeDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Commission A Second Screening',
            preview: 'More data, more delay.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },

    {
      id: 'viral-set-moment',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['production', 'postProduction'],
      title: 'Viral Set Leak',
      decisionTitle: 'Viral Set Leak',
      body: "An unplanned on-set moment was captured on a crew member's phone. It's spreading. You didn't plan this.",
      cooldownWeeks: 6,
      baseWeight: 1.0,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Viral Set Leak',
        body: projectTitle
          ? `An unplanned moment from ${projectTitle}'s set is spreading online. Your marketing team is watching the numbers climb.`
          : "An unplanned on-set moment is spreading online. Your marketing team is watching the numbers climb.",
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Own It — Release Official Version',
            preview: 'Maximum audience reach. Critics notice the engineered enthusiasm.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 5,
            criticsDelta: -1,
            audienceDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Issue Takedown',
            preview: 'Controlled brand. Costs goodwill.',
            cashDelta: -80_000,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            criticsDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Stay Quiet',
            preview: 'Organic spread. Limited upside.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'critic-embargo-request',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      title: 'Critics Guild Embargo Lift',
      decisionTitle: 'Critics Guild Embargo Lift',
      body: 'A respected critics bloc is requesting an early embargo lift to align with their awards calendar. Your current cut would have to hold up.',
      cooldownWeeks: 5,
      baseWeight: 0.95,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Critics Guild Embargo Lift',
        body: projectTitle
          ? `A critics bloc wants an early embargo lift on ${projectTitle} to align with their awards cycle.`
          : 'A critics bloc wants an early embargo lift to align with their awards cycle.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Lift For Qualifying Outlets',
            preview: "High reward if the film holds. High exposure if it doesn't.",
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            criticsDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Maintain Full Embargo',
            preview: "Standard call. Minor critics friction.",
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Advance Access To Select Critics',
            preview: 'Careful version. Costs a little, risks a little less.',
            cashDelta: -60_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'campaign-repositioning',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      title: 'Campaign Reposition Window',
      decisionTitle: 'Campaign Reposition Window',
      body: "Test audience data shows the campaign is emphasizing the wrong elements. A pivot is still possible before wide release.",
      cooldownWeeks: 6,
      baseWeight: 1.0,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Campaign Reposition Window',
        body: projectTitle
          ? `Campaign data for ${projectTitle} is pointing the wrong direction. There's still time to pivot before wide release.`
          : "Campaign data is pointing the wrong direction. There's still time to pivot before wide release.",
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Rebuild Around Emotional Hook',
            preview: 'Expensive. Broadens the tent.',
            cashDelta: -280_000,
            scriptQualityDelta: 0,
            hypeDelta: 4,
            audienceDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Lean Into Genre Signifiers',
            preview: 'Cheaper repositioning. Trades prestige for attendance.',
            cashDelta: -140_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            criticsDelta: -1,
            audienceDelta: 3,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Current Campaign',
            preview: 'Saves money. Accepts current ceiling.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
];
