import type { EventTemplate } from '../../types';

export const studioStrategyEvents: EventTemplate[] = [
{
      id: 'first-look-term-sheet',
      category: 'talent',
      scope: 'studio',
      title: 'First-Look Term Sheet',
      decisionTitle: 'First-Look Term Sheet',
      body: 'A major agency is offering an exclusive first-look deal on new material — upfront cost, ongoing script access.',
      cooldownWeeks: 12,
      baseWeight: 0.85,
      minWeek: 5,
      buildDecision: ({ idFactory, currentWeek }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'talent',
        title: 'First-Look Term Sheet',
        body: 'A major agency is offering exclusive first-look rights on new writer and director packages. Upfront cost, long-term pipeline access.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Sign The Deal',
            preview: 'Better talent pipeline access. Costs independence.',
            cashDelta: -340_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            talentRepDelta: 2,
            setFlag: 'first_look_active',
          },
          {
            id: idFactory('opt'),
            label: 'Pass — Stay Open Market',
            preview: 'No upfront. Slight signal of self-reliance.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: -1,
            distributorRepDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'year-end-snub',
      category: 'marketing',
      scope: 'studio',
      title: 'Year-End Recognition Snub',
      decisionTitle: 'Year-End Recognition Snub',
      body: "A significant industry list omits your studio entirely. The gap between your output and the industry's perception of you is showing.",
      cooldownWeeks: 18,
      baseWeight: 0.8,
      minWeek: 8,
      buildDecision: ({ idFactory, currentWeek }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'marketing',
        title: 'Year-End Recognition Snub',
        body: "A major year-end industry list passed your studio over. The gap between your work and your reputation is public now.",
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Commission A Trade Campaign',
            preview: 'Costs money. Makes the case.',
            cashDelta: -200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 2,
            audienceDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Let The Work Speak',
            preview: 'No spend. Slightly better than nothing.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
          },
        ],
      }),
    },

    {
      id: 'acquisition-rumor',
      category: 'finance',
      scope: 'studio',
      blocksFlag: 'independence_declared',
      title: 'Acquisition Rumor',
      decisionTitle: 'Acquisition Rumor',
      body: 'Trade press is running a story that a major studio is interested in acquiring your catalog and key talent relationships.',
      cooldownWeeks: 15,
      baseWeight: 0.9,
      minWeek: 10,
      buildDecision: ({ idFactory, currentWeek }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Acquisition Rumor',
        body: "Trade press is running acquisition speculation. Your team is asking questions. How you respond sets the tone.",
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Issue A Strong Denial',
            preview: 'Reassures your people. Closes the story.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: 1,
            distributorRepDelta: 1,
            setFlag: 'independence_declared',
          },
          {
            id: idFactory('opt'),
            label: 'Stay Quiet',
            preview: 'Attention without commitment. Staff reads into it.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            talentRepDelta: -1,
          },
          {
            id: idFactory('opt'),
            label: 'Engage Exploratory Talks',
            preview: 'Pure profile play. Real internal cost.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            talentRepDelta: -2,
            audienceDelta: 2,
          },
        ],
      }),
    },

    {
      id: 'co-production-offer',
      category: 'finance',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Co-Production Offer',
      decisionTitle: 'Co-Production Offer',
      body: 'An international studio proposes co-production terms — shared cost, shared credit, and a required international location pivot.',
      cooldownWeeks: 7,
      baseWeight: 1.0,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle, currentWeek }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Co-Production Offer',
        body: projectTitle
          ? `An international studio wants to co-produce ${projectTitle}. Shared cost, shared credit, mandatory location pivot.`
          : 'An international studio wants to co-produce. Shared cost, shared credit, mandatory location pivot.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Co-Production Terms',
            preview: 'Risk-sharing at the cost of creative control and timeline.',
            cashDelta: 380_000,
            scriptQualityDelta: -0.2,
            hypeDelta: -1,
            scheduleDelta: 1,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Counter With Equity-Only Terms',
            preview: 'Smaller cash. Keeps creative authority.',
            cashDelta: 180_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Decline',
            preview: 'Clean. No cash.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },

    {
      id: 'completion-bond-audit',
      category: 'finance',
      scope: 'project',
      targetPhases: ['production', 'postProduction'],
      title: 'Completion Bond Audit',
      decisionTitle: 'Completion Bond Audit',
      body: 'Bond underwriters request a compliance review before they keep covering late-stage risk.',
      cooldownWeeks: 12,
      baseWeight: 0.72,
      minWeek: 10,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Completion Bond Audit',
        body: projectTitle
          ? `Underwriters want a fast audit pass on ${projectTitle} before they confirm full completion coverage.`
          : 'Underwriters want a fast audit pass before they confirm full completion coverage.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Open Full Books',
            preview: 'Most expensive. Buys strongest confidence.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            criticsDelta: 1,
            distributorRepDelta: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Negotiate Limited Access',
            preview: 'Middle path with minor process drag.',
            cashDelta: -60_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: 1,
            scheduleDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Refuse The Audit',
            preview: 'No cost now. Relationship damage later.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            distributorRepDelta: -2,
            audienceDelta: -1,
          },
        ],
      }),
    },
];
