import type { EventTemplate } from '../../types';

export const foundationCoreEvents: EventTemplate[] = [
{
      id: 'rewrite-window',
      category: 'creative',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Rewrite Window',
      decisionTitle: 'Rewrite Pass Opportunity',
      body: 'A top script doctor opens a one-week slot.',
      cooldownWeeks: 3,
      baseWeight: 1.4,
      minWeek: 1,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Rewrite Pass Opportunity',
        body: `${projectTitle ?? 'A project'} can book a premium rewrite pass this week only.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Approve Rewrite',
            preview: 'Script quality improves and development confidence rises.',
            cashDelta: -140_000,
            scriptQualityDelta: 0.6,
            hypeDelta: 1,
            setFlag: 'rewrite_invested',
          },
          {
            id: idFactory('opt'),
            label: 'Decline',
            preview: 'Save cash and move on with current pages.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'financier-notes',
      category: 'finance',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      blocksArc: { id: 'financier-control', status: 'resolved' },
      title: 'Financier Notes Pass',
      decisionTitle: 'Financier Notes Request',
      body: 'A co-financier offers cash now in exchange for script notes and control.',
      cooldownWeeks: 4,
      baseWeight: 1,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'financier-control',
        arcStage: 0,
        title: 'Financier Notes Request',
        body: `${projectTitle ?? 'The project'} can secure early money if you accept commercial notes.`,
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Take The Cash',
            preview: 'Immediate runway boost, but creative compromise.',
            cashDelta: 220_000,
            scriptQualityDelta: -0.4,
            hypeDelta: -1,
            studioHeatDelta: -1,
            setFlag: 'financier_control',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Hold Creative Line',
            preview: 'No cash injection, but your brand strength improves.',
            cashDelta: 0,
            scriptQualityDelta: 0.1,
            hypeDelta: 1,
            studioHeatDelta: 1,
            clearFlag: 'financier_control',
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'table-read-breakthrough',
      category: 'creative',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Table Read Breakthrough',
      decisionTitle: 'Table Read Discovery',
      body: 'A table read reveals a stronger emotional direction.',
      cooldownWeeks: 5,
      baseWeight: 1.1,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        title: 'Table Read Discovery',
        body: `${projectTitle ?? 'The script'} has a chance to improve with one focused polish sprint.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund A Polish Sprint',
            preview: 'Sharper pages and stronger cast confidence.',
            cashDelta: -180_000,
            scriptQualityDelta: 0.4,
            hypeDelta: 2,
            studioHeatDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Lock Current Draft',
            preview: 'No new spend, but less momentum at this stage.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
    {
      id: 'financier-mandate-rewrite',
      category: 'finance',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      requiresArc: { id: 'financier-control', minStage: 1, status: 'active' },
      title: 'Financier Mandate Rewrite',
      decisionTitle: 'Mandatory Financier Changes',
      body: 'The financing partner now demands scene and casting adjustments mid-process.',
      cooldownWeeks: 6,
      baseWeight: 1.1,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'financier-control',
        arcStage: 1,
        title: 'Mandatory Financier Changes',
        body: `${projectTitle ?? 'The project'} must decide whether to accept deeper mandate clauses.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Mandate',
            preview: 'Secure added cash but sacrifice quality and autonomy.',
            cashDelta: 380_000,
            scriptQualityDelta: -0.5,
            hypeDelta: -2,
            studioHeatDelta: -2,
            setArcStage: 2,
            setFlag: 'financier_control',
          },
          {
            id: idFactory('opt'),
            label: 'Buy Out Clause',
            preview: 'Pay to regain control and restore creative momentum.',
            cashDelta: -420_000,
            scriptQualityDelta: 0.3,
            hypeDelta: 2,
            studioHeatDelta: 2,
            clearFlag: 'financier_control',
            resolveArc: true,
          },
        ],
      }),
    },
    {
      id: 'financier-test-screening-fallout',
      category: 'creative',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      requiresArc: { id: 'financier-control', minStage: 2, status: 'active' },
      title: 'Financier Cut Fallout',
      decisionTitle: 'Test Screening Damage Control',
      body: 'Audience scores crater after the mandated cut strategy leaks to press.',
      cooldownWeeks: 7,
      baseWeight: 1,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'creative',
        arcId: 'financier-control',
        arcStage: 2,
        title: 'Test Screening Damage Control',
        body: `${projectTitle ?? 'The title'} can attempt a late recovery edit before release.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Re-cut For Cohesion',
            preview: 'Expensive rescue pass with upside on quality and heat.',
            cashDelta: -360_000,
            scriptQualityDelta: 0.5,
            hypeDelta: 2,
            studioHeatDelta: 2,
            clearFlag: 'financier_control',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Ship As Is',
            preview: 'Protect cash now but absorb long-tail brand damage.',
            cashDelta: 0,
            scriptQualityDelta: -0.2,
            hypeDelta: -3,
            studioHeatDelta: -3,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'tax-credit-window',
      category: 'finance',
      scope: 'project',
      targetPhases: ['preProduction', 'production'],
      title: 'Tax Credit Window',
      decisionTitle: 'Regional Tax Credit Offer',
      body: 'A region opens a short-lived incentive program with strict timing.',
      cooldownWeeks: 4,
      baseWeight: 1.15,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Regional Tax Credit Offer',
        body: `${projectTitle ?? 'The production'} can qualify if logistics move now.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Relocate Unit',
            preview: 'Front-load spend to reduce long-tail schedule and risk.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            scheduleDelta: -1,
            overrunRiskDelta: -0.08,
          },
          {
            id: idFactory('opt'),
            label: 'Stay Put',
            preview: 'Keep production stable and avoid relocation churn.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
    {
      id: 'crew-morale-check',
      category: 'operations',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Crew Morale Warning',
      decisionTitle: 'Crew Morale Intervention',
      body: 'Line producers report burnout risk across key departments.',
      cooldownWeeks: 3,
      baseWeight: 1.2,
      minWeek: 2,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Crew Morale Intervention',
        body: `${projectTitle ?? 'This production'} is showing fatigue indicators.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Add Relief Crew',
            preview: 'Costly now, but stabilizes execution and press sentiment.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            studioHeatDelta: 1,
            overrunRiskDelta: -0.05,
          },
          {
            id: idFactory('opt'),
            label: 'Push Through',
            preview: 'Stay on spend, but pressure and overrun risk increase.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            scheduleDelta: -1,
            overrunRiskDelta: 0.06,
          },
        ],
      }),
    },
    {
      id: 'stunt-coordinator-overscoped',
      category: 'operations',
      scope: 'project',
      targetPhases: ['preProduction'],
      title: 'Stunt Coordinator Overscoped',
      decisionTitle: 'Stunt Scope Reset',
      body: 'The stunt package is oversized for your prep timeline and current cash posture.',
      cooldownWeeks: 5,
      baseWeight: 1.05,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Stunt Scope Reset',
        body: `${projectTitle ?? 'The project'} can lock a leaner action plan or pay to keep the full package.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Keep Full Stunt Package',
            preview: 'Bigger spectacle upside, heavier prep pressure.',
            cashDelta: -280_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            overrunRiskDelta: 0.05,
          },
          {
            id: idFactory('opt'),
            label: 'Trim Scope To Core Setpieces',
            preview: 'Lower execution risk with modest hype loss.',
            cashDelta: -140_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            overrunRiskDelta: -0.06,
          },
          {
            id: idFactory('opt'),
            label: 'Reboard Internally',
            preview: 'No immediate spend, but prep takes a week and momentum softens.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            scheduleDelta: 1,
            overrunRiskDelta: -0.02,
          },
        ],
      }),
    },
    {
      id: 'location-dispute',
      category: 'operations',
      scope: 'project',
      targetPhases: ['preProduction'],
      title: 'Location Dispute',
      decisionTitle: 'Location Access Dispute',
      body: 'A local dispute blocks your planned locations just before lock.',
      cooldownWeeks: 5,
      baseWeight: 1.08,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Location Access Dispute',
        body: `${projectTitle ?? 'The production'} needs a location strategy decision this week.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Pay Local Settlement',
            preview: 'Keep your schedule and avoid public friction.',
            cashDelta: -190_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Relocate The Unit',
            preview: 'Cheaper in cash, but prep slips and logistics risk rises.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            scheduleDelta: 1,
            overrunRiskDelta: 0.03,
          },
          {
            id: idFactory('opt'),
            label: 'Wait Out The Dispute',
            preview: 'No cash now, but momentum and timing take a hit.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            scheduleDelta: 2,
          },
        ],
      }),
    },
    {
      id: 'practical-stunt-package',
      category: 'operations',
      scope: 'project',
      targetPhases: ['production'],
      title: 'Practical Stunt Package',
      decisionTitle: 'Practical Stunt Upgrade',
      body: 'A top stunt team can execute a real sequence the VFX route cannot match.',
      cooldownWeeks: 5,
      baseWeight: 1.05,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Practical Stunt Upgrade',
        body: `${projectTitle ?? 'The production'} can pivot toward a practical centerpiece shot.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Greenlight Practical Unit',
            preview: 'Bigger buzz and authenticity, but heavier execution risk.',
            cashDelta: -320_000,
            scriptQualityDelta: 0,
            hypeDelta: 5,
            overrunRiskDelta: 0.04,
          },
          {
            id: idFactory('opt'),
            label: 'Stay VFX-Heavy',
            preview: 'Safer operating profile with a smaller hype upside.',
            cashDelta: -80_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            overrunRiskDelta: -0.02,
          },
          {
            id: idFactory('opt'),
            label: 'Decline the Package',
            preview: 'No spend. The opportunity passes; production continues as-is.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            overrunRiskDelta: 0,
          },
        ],
      }),
    },
    {
      id: 'post-pipeline-upgrade',
      category: 'operations',
      scope: 'project',
      targetPhases: ['postProduction'],
      title: 'Post Pipeline Upgrade',
      decisionTitle: 'Post Pipeline Decision',
      body: 'Editorial can move to a faster pipeline this week with vendor support.',
      cooldownWeeks: 4,
      baseWeight: 1.05,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        title: 'Post Pipeline Decision',
        body: `${projectTitle ?? 'Post'} can lock picture faster with outside support.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Buy Vendor Upgrade',
            preview: 'Reduce delay risk and tighten release readiness.',
            cashDelta: -240_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            scheduleDelta: -1,
            overrunRiskDelta: -0.05,
          },
          {
            id: idFactory('opt'),
            label: 'Keep Current Pipeline',
            preview: 'No spend now, but timeline remains fragile.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
          },
        ],
      }),
    },
];
