import type { EventTemplate } from '../../types';

export const franchisePivotCoreEvents: EventTemplate[] = [
{
      id: 'franchise-rights-window',
      category: 'finance',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      blocksArc: { id: 'franchise-pivot', status: 'resolved' },
      title: 'Franchise Rights Window',
      decisionTitle: 'Franchise Rights Reversion',
      body: 'Underlying rights for follow-up stories can be locked now before outside bidders move.',
      cooldownWeeks: 9,
      baseWeight: 0.85,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'franchise-pivot',
        arcStage: 0,
        title: 'Franchise Rights Reversion',
        body: `${projectTitle ?? 'The property'} can become a long-tail asset if you commit early.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Secure Sequel Rights',
            preview: 'Upfront spend for future optionality and leverage.',
            cashDelta: -420_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 1,
            setFlag: 'franchise_rights',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Pass On Rights',
            preview: 'Stay focused on current slate and preserve capital.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'universe-room-pitch',
      category: 'creative',
      scope: 'studio',
      requiresArc: { id: 'franchise-pivot', minStage: 1, status: 'active' },
      title: 'Universe Room Proposal',
      decisionTitle: 'Franchise Room Summit',
      body: 'Development proposes a connected slate room for sequel and spin-off planning.',
      cooldownWeeks: 10,
      baseWeight: 0.9,
      minWeek: 10,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'creative',
        arcId: 'franchise-pivot',
        arcStage: 1,
        title: 'Franchise Room Summit',
        body: 'Commit to a universe strategy now or keep a standalone identity.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Fund Franchise Room',
            preview: 'Strategic depth and long-tail upside at real annual cost.',
            cashDelta: -360_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            setArcStage: 2,
            setFlag: 'franchise_room',
          },
          {
            id: idFactory('opt'),
            label: 'Keep Standalone Focus',
            preview: 'Protect flexibility and avoid sequel pressure.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: 1,
            clearFlag: 'franchise_room',
            resolveArc: true,
          },
        ],
      }),
    },
    {
      id: 'flagship-greenlight-crossroads',
      category: 'creative',
      scope: 'studio',
      requiresArc: { id: 'franchise-pivot', minStage: 2, status: 'active' },
      title: 'Flagship Greenlight Crossroads',
      decisionTitle: 'Franchise Flagship Decision',
      body: 'Board asks for final call: flagship sequel slate or return to originals-only mandate.',
      cooldownWeeks: 12,
      baseWeight: 0.8,
      minWeek: 12,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'creative',
        arcId: 'franchise-pivot',
        arcStage: 2,
        title: 'Franchise Flagship Decision',
        body: 'This choice defines studio identity for the next cycle.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Commit To Flagship Franchise',
            preview: 'Higher commercial ceiling with stronger volatility profile.',
            cashDelta: -520_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            studioHeatDelta: 3,
            setFlag: 'franchise_committed',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Return To Originals',
            preview: 'Lower upside but cleaner creative identity and balance.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            clearFlag: 'franchise_room',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Delay Strategic Decision',
            preview: 'Short-term flexibility at long-term credibility cost.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            studioHeatDelta: -2,
            failArc: true,
          },
        ],
      }),
    },
];
