import type { EventTemplate } from '../../types';

export const marketFinanceCoreEvents: EventTemplate[] = [
{
      id: 'premium-trailer-placement',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['postProduction', 'distribution'],
      title: 'Trailer Slot',
      decisionTitle: 'Premium Trailer Placement',
      body: 'A distributor opens premium trailer placement for a short window.',
      cooldownWeeks: 4,
      baseWeight: 1.1,
      minWeek: 3,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        title: 'Premium Trailer Placement',
        body: `${projectTitle ?? 'The title'} can buy premium placement now or hold spend for later.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Buy Placement',
            preview: 'Higher awareness and stronger opening readiness.',
            cashDelta: -330_000,
            scriptQualityDelta: 0,
            hypeDelta: 6,
            marketingDelta: 250_000,
          },
          {
            id: idFactory('opt'),
            label: 'Pass',
            preview: 'Keep powder dry for a later marketing burst.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
    {
      id: 'brand-integration-deal',
      category: 'finance',
      scope: 'project',
      targetPhases: ['production', 'distribution'],
      title: 'Brand Integration Offer',
      decisionTitle: 'Brand Integration Deal',
      body: 'A consumer brand offers placement money with approval rights.',
      cooldownWeeks: 5,
      baseWeight: 1,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        title: 'Brand Integration Deal',
        body: `${projectTitle ?? 'The project'} can lock an integration package this week.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Take The Deal',
            preview: 'Improves cash, but creative perception softens slightly.',
            cashDelta: 450_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: -1,
            setFlag: 'brand_partner',
          },
          {
            id: idFactory('opt'),
            label: 'Decline',
            preview: 'No new money, but preserves brand identity.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: 1,
          },
        ],
      }),
    },
    {
      id: 'bridge-financing',
      category: 'finance',
      scope: 'studio',
      title: 'Bridge Financing Offer',
      decisionTitle: 'Bridge Financing Term Sheet',
      body: 'A lender offers a short facility to smooth production cashflow.',
      cooldownWeeks: 7,
      baseWeight: 0.9,
      minWeek: 2,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        title: 'Bridge Financing Term Sheet',
        body: 'The facility gives breathing room now but can hurt your heat if overused.',
        weeksUntilExpiry: 2,
        options: [
          {
            id: idFactory('opt'),
            label: 'Draw Facility',
            preview: 'Immediate cash cushion at reputation cost.',
            cashDelta: 1_200_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: -2,
            setFlag: 'bridge_debt',
          },
          {
            id: idFactory('opt'),
            label: 'Stay Lean',
            preview: 'No debt draw and stronger market discipline signal.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 1,
            clearFlag: 'bridge_debt',
          },
        ],
      }),
    },
    {
      id: 'agency-package-push',
      category: 'talent',
      scope: 'project',
      targetPhases: ['development', 'preProduction'],
      title: 'Agency Package Push',
      decisionTitle: 'Agency Packaging Proposal',
      body: 'A major agency offers a packaged talent bundle with a short deadline.',
      cooldownWeeks: 5,
      baseWeight: 0.95,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        title: 'Agency Packaging Proposal',
        body: `${projectTitle ?? 'The project'} can move faster if you accept packaged attachments.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Package Terms',
            preview: 'Faster schedule and buzz, with a meaningful upfront cost.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            scheduleDelta: -1,
            studioHeatDelta: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Run Open Market',
            preview: 'Keep flexibility and preserve cash.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
          },
        ],
      }),
    },
];
