import type { EventTemplate } from '../../types';

export const talentExhibitorCoreEvents: EventTemplate[] = [
{
      id: 'star-renegotiation-shock',
      category: 'talent',
      scope: 'project',
      targetPhases: ['production', 'postProduction'],
      blocksArc: { id: 'talent-meltdown', status: 'resolved' },
      title: 'Star Renegotiation Shock',
      decisionTitle: 'Star Renegotiation Ultimatum',
      body: 'Lead talent requests major contract revisions after early buzz tracking.',
      cooldownWeeks: 7,
      baseWeight: 0.95,
      minWeek: 4,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        arcId: 'talent-meltdown',
        arcStage: 0,
        title: 'Star Renegotiation Ultimatum',
        body: `${projectTitle ?? 'The production'} has 48 hours to answer talent demands.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Pay Upfront Premium',
            preview: 'Stabilize set now but set a costly precedent.',
            cashDelta: -340_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            setArcStage: 1,
            setFlag: 'star_fragile',
          },
          {
            id: idFactory('opt'),
            label: 'Hold Firm On Terms',
            preview: 'Save money now with elevated blowback risk.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            studioHeatDelta: -1,
            setArcStage: 1,
            setFlag: 'star_fragile',
          },
        ],
      }),
    },
    {
      id: 'tabloid-on-set-leak',
      category: 'talent',
      scope: 'project',
      targetPhases: ['production', 'postProduction', 'distribution'],
      requiresArc: { id: 'talent-meltdown', minStage: 1, status: 'active' },
      title: 'Tabloid Set Leak',
      decisionTitle: 'Star PR Crisis',
      body: 'A tabloid leak alleges toxic on-set behavior around your lead talent.',
      cooldownWeeks: 8,
      baseWeight: 1.05,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        arcId: 'talent-meltdown',
        arcStage: 1,
        title: 'Star PR Crisis',
        body: `${projectTitle ?? 'The title'} now faces a narrative war before release.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Back Talent Publicly',
            preview: 'Defend the star, protect hype, risk credibility hit if it worsens.',
            cashDelta: -110_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: -1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Neutral Compliance Statement',
            preview: 'Lower volatility path with moderate trust rebuild.',
            cashDelta: -80_000,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            studioHeatDelta: 1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Quiet Settlement Package',
            preview: 'Expensive containment; likely closes the incident cycle.',
            cashDelta: -260_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            studioHeatDelta: 2,
            clearFlag: 'star_fragile',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'No Comment',
            preview: 'Stay silent. Story may escalate, but no cash spent.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -3,
            studioHeatDelta: -2,
            setArcStage: 2,
          },
        ],
      }),
    },
    {
      id: 'talent-endgame-judgment',
      category: 'talent',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresArc: { id: 'talent-meltdown', minStage: 2, status: 'active' },
      title: 'Talent Endgame Judgment',
      decisionTitle: 'Final Talent Fallout Decision',
      body: 'Distributors demand confidence in campaign leadership before final push.',
      cooldownWeeks: 9,
      baseWeight: 0.9,
      minWeek: 8,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'talent',
        arcId: 'talent-meltdown',
        arcStage: 2,
        title: 'Final Talent Fallout Decision',
        body: `${projectTitle ?? 'The campaign'} must choose between loyalty, replacement optics, or retreat.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Stand By Star',
            preview: 'High-risk loyalty play with major upside if audience follows.',
            cashDelta: -140_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            studioHeatDelta: -1,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Reframe Campaign Around Craft',
            preview: 'Costly pivot that de-emphasizes personality narrative.',
            cashDelta: -220_000,
            scriptQualityDelta: 0.2,
            hypeDelta: 1,
            studioHeatDelta: 2,
            clearFlag: 'star_fragile',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Slash Exposure And Coast',
            preview: 'Protect remaining budget at clear momentum cost.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -3,
            studioHeatDelta: -3,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'exclusivity-term-sheet',
      category: 'finance',
      scope: 'project',
      targetPhases: ['distribution'],
      blocksArc: { id: 'exhibitor-war', status: 'resolved' },
      title: 'Exhibitor Exclusivity Demand',
      decisionTitle: 'Exclusivity Term Sheet',
      body: 'Top exhibitors offer premium screens in exchange for stricter exclusivity terms.',
      cooldownWeeks: 7,
      baseWeight: 1.05,
      minWeek: 6,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'exhibitor-war',
        arcStage: 0,
        title: 'Exclusivity Term Sheet',
        body: `${projectTitle ?? 'The release'} can gain footprint now, but at strategic cost.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Accept Hard Exclusivity',
            preview: 'Better placement now; narrower flexibility later.',
            cashDelta: 280_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            setArcStage: 1,
            setFlag: 'exhibitor_locked',
          },
          {
            id: idFactory('opt'),
            label: 'Negotiate Flexible Terms',
            preview: 'Smaller upside now with strategic flexibility preserved.',
            cashDelta: 120_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Decline And Stay Flexible',
            preview: 'No immediate cash, but avoids dependency.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'rival-screen-squeeze',
      category: 'operations',
      scope: 'project',
      targetPhases: ['distribution', 'released'],
      requiresArc: { id: 'exhibitor-war', minStage: 1, status: 'active' },
      title: 'Rival Screen Squeeze',
      decisionTitle: 'Screen Share Countermove',
      body: 'A rival studio books aggressive previews and threatens your prime slots.',
      cooldownWeeks: 8,
      baseWeight: 1.1,
      minWeek: 7,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'operations',
        arcId: 'exhibitor-war',
        arcStage: 1,
        title: 'Screen Share Countermove',
        body: `${projectTitle ?? 'The release'} must react before allocations lock.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Pay Local Exhibitor Support',
            preview: 'Defend footprint with targeted spend.',
            cashDelta: -240_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Shift To Alternate Markets',
            preview: 'Reduce conflict but soften domestic launch optics.',
            cashDelta: -90_000,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            studioHeatDelta: 0,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Hold And Absorb',
            preview: 'No spend now; risk deeper slot erosion.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            studioHeatDelta: -1,
            setArcStage: 2,
          },
        ],
      }),
    },
    {
      id: 'opening-weekend-lockout',
      category: 'finance',
      scope: 'project',
      targetPhases: ['released'],
      requiresArc: { id: 'exhibitor-war', minStage: 2, status: 'active' },
      title: 'Opening Weekend Lockout Threat',
      decisionTitle: 'Exhibitor Lockout Crisis',
      body: 'Two chains threaten reduced showtimes unless terms are amended before weekend.',
      cooldownWeeks: 10,
      baseWeight: 0.95,
      minWeek: 9,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'finance',
        arcId: 'exhibitor-war',
        arcStage: 2,
        title: 'Exhibitor Lockout Crisis',
        body: `${projectTitle ?? 'The title'} is one negotiation away from a major footprint swing.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Concede Revenue Points',
            preview: 'Pay through split to secure broad weekend access.',
            cashDelta: -300_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            studioHeatDelta: 1,
            clearFlag: 'exhibitor_locked',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Pivot To Premium + Events',
            preview: 'Smaller footprint, higher intensity rollout.',
            cashDelta: -160_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            studioHeatDelta: 2,
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Refuse Terms',
            preview: 'Protect principles and cash, accept opening damage.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -4,
            studioHeatDelta: -3,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'exhibitor-summit-invite',
      category: 'finance',
      scope: 'studio',
      blocksArc: { id: 'exhibitor-power-play', status: 'resolved' },
      title: 'Exhibitor Summit Invite',
      decisionTitle: 'Exhibitor Summit Invitation',
      body: 'Major chains invite your studio to lock preferred screen commitments for the next cycle.',
      cooldownWeeks: 9,
      baseWeight: 0.68,
      minWeek: 8,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        arcId: 'exhibitor-power-play',
        arcStage: 0,
        title: 'Exhibitor Summit Invitation',
        body: 'Sign premium terms, take a smaller regional deal, or stay fully independent for this cycle.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Sign Premium Screen Commitment',
            preview: 'Higher placement confidence with tighter chain expectations.',
            cashDelta: 220_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            distributorRepDelta: 3,
            audienceDelta: 1,
            setFlag: 'exhibitor_priority',
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Take Regional Partner Deal',
            preview: 'Lower-cost footprint gains with fewer commitments.',
            cashDelta: 100_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            distributorRepDelta: 1,
            audienceDelta: 1,
            setArcStage: 1,
          },
          {
            id: idFactory('opt'),
            label: 'Stay Independent',
            preview: 'No spend now. Chains treat your slate as lower priority.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: 0,
            distributorRepDelta: -1,
            criticsDelta: 1,
            failArc: true,
          },
        ],
      }),
    },
    {
      id: 'release-window-showdown',
      category: 'marketing',
      scope: 'project',
      targetPhases: ['distribution'],
      requiresArc: { id: 'exhibitor-power-play', minStage: 1, status: 'active' },
      title: 'Release Window Showdown',
      decisionTitle: 'Release Window Showdown',
      body: 'Competing studios crowd your date and exhibitors want certainty before locking final allocations.',
      cooldownWeeks: 10,
      baseWeight: 0.74,
      minWeek: 10,
      buildDecision: ({ idFactory, projectId, projectTitle }) => ({
        id: idFactory('decision'),
        projectId,
        category: 'marketing',
        arcId: 'exhibitor-power-play',
        arcStage: 1,
        title: 'Release Window Showdown',
        body: `${projectTitle ?? 'The release'} needs a date strategy before chain allocations finalize.`,
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Hold Prime Date',
            preview: 'Spend to protect footprint and opening-week narrative.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 3,
            distributorRepDelta: 2,
            audienceDelta: 1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Move To Cleaner Corridor',
            preview: 'Lower conflict and steadier reviews with reduced launch heat.',
            cashDelta: -40_000,
            scriptQualityDelta: 0,
            hypeDelta: 1,
            criticsDelta: 1,
            audienceDelta: 1,
            setArcStage: 2,
          },
          {
            id: idFactory('opt'),
            label: 'Accept A Late Delay',
            preview: 'Cheapest immediate option, but momentum slips.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -2,
            audienceDelta: -1,
            setArcStage: 2,
          },
        ],
      }),
    },
    {
      id: 'theatrical-identity-vote',
      category: 'finance',
      scope: 'studio',
      requiresArc: { id: 'exhibitor-power-play', minStage: 2, status: 'active' },
      title: 'Theatrical Identity Vote',
      decisionTitle: 'Theatrical Identity Vote',
      body: 'Your board wants a clear theatrical strategy before the next slate is greenlit.',
      cooldownWeeks: 12,
      baseWeight: 0.7,
      minWeek: 12,
      buildDecision: ({ idFactory }) => ({
        id: idFactory('decision'),
        projectId: null,
        category: 'finance',
        arcId: 'exhibitor-power-play',
        arcStage: 2,
        title: 'Theatrical Identity Vote',
        body: 'Choose wide-opening scale, prestige platforming discipline, or stay indecisive and absorb the credibility cost.',
        weeksUntilExpiry: 1,
        options: [
          {
            id: idFactory('opt'),
            label: 'Commit To Wide-Opening Dominance',
            preview: 'Big commercial posture with heavier spend and critic skepticism.',
            cashDelta: -120_000,
            scriptQualityDelta: 0,
            hypeDelta: 2,
            audienceDelta: 3,
            distributorRepDelta: 2,
            criticsDelta: -1,
            setFlag: 'wide_release_identity',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'Commit To Prestige Platforming',
            preview: 'Sharper critical posture with a slower commercial ramp.',
            cashDelta: -80_000,
            scriptQualityDelta: 0.1,
            hypeDelta: 1,
            criticsDelta: 3,
            talentRepDelta: 2,
            audienceDelta: 1,
            setFlag: 'prestige_rollout_identity',
            resolveArc: true,
          },
          {
            id: idFactory('opt'),
            label: 'No Clear Identity',
            preview: 'Preserves optionality now, weakens confidence everywhere.',
            cashDelta: 0,
            scriptQualityDelta: 0,
            hypeDelta: -1,
            audienceDelta: -2,
            distributorRepDelta: -2,
            talentRepDelta: -1,
            failArc: true,
          },
        ],
      }),
    },
];
